# **Modelling the Spread of Rent Inflation across States in the US through a Combined Spatial Analysis and Diffusion Modeling Approach**

<br>

<br>

*Week 2- Data Collection, Data Cleaning, Data Transformation, Data Aggregation and Feature Engineering*

## Rent Inflation Data - HUD Data

### Data Collection

In [2]:
import requests
import pandas as pd
from io import BytesIO
import numpy as np


# Loading links to datasets 2001-2026
with open("HUDUSER-HousingDataLinks.txt", "r") as f:
    urls = [line.strip() for line in f if line.strip()]

urls

['https://www.huduser.gov/portal/datasets/50thper/FY2026_FMR_50_county.xlsx',
 'https://www.huduser.gov/portal/datasets/50thper/FY2025_FMR_50_county.xlsx',
 'https://www.huduser.gov/portal/datasets/50thper/FY2024_FMR_50_county_revised.xlsx',
 'https://www.huduser.gov/portal/datasets/50thper/FY2023_FMR_50_county_rev.xlsx',
 'https://www.huduser.gov/portal/datasets/50thper/FY2022_FMR_50_county_rev.xlsx',
 'https://www.huduser.gov/portal/datasets/50thper/FY2021_50_County.xlsx',
 'https://www.huduser.gov/portal/datasets/50thper/FY2020_50_County_rev.xlsx',
 'https://www.huduser.gov/portal/datasets/50thper/FY2019_50_County_rev.xlsx',
 'https://www.huduser.gov/portal/datasets/50thper/FY2018_50_County_rev.xlsx',
 'https://www.huduser.gov/portal/datasets/50thper/FY2017_50_rev.xlsx',
 'https://www.huduser.gov/portal/datasets/50thper/FY2016F_50_RevFinal.xlsx',
 'https://www.huduser.gov/portal/datasets/50thper/FY2015_50_RevFinal.xls',
 'https://www.huduser.gov/portal/datasets/50thper/FY2014_50_RevFinal.xls',
 'https://www.huduser.gov/portal/datasets/50thper/FY2013_50_Final.xls',
 'https://www.huduser.gov/portal/datasets/50thper/FY2012_FMRS_50_County.xls',
 'https://www.huduser.gov/portal/datasets/50thper/FY2011_50_Final_County.xls',
 'https://www.huduser.gov/portal/datasets/50thper/FY2010_50_Final.xls',
 'https://www.huduser.gov/portal/datasets/50thper/FY2009_50_Rev_Final.xls',
 'https://www.huduser.gov/portal/datasets/50thper/FY2008_county_level_50th_r.xls',
 'https://www.huduser.gov/portal/datasets/50thper/FY2007_County_Level_50th.xls',
 'https://www.huduser.gov/portal/datasets/50thper/FY2006_County_Level_50th.xls',
 'https://www.huduser.gov/portal/datasets/50thper/County_Level_50.xls',
 'https://www.huduser.gov/portal/datasets/50thper/FMR2004F50_County.xls',
 'https://www.huduser.gov/portal/datasets/50thper/FY2003_50Rents_County.xls',
 'https://www.huduser.gov/portal/datasets/50thper/FY2002_50th.xls',
 'https://www.huduser.gov/portal/datasets/50thper/FY2001_50th.xls']

In [11]:
%pip install selenium webdriver-manager openpyxl xlrd

Requirement already satisfied: selenium in /usr/local/lib/python3.12/dist-packages (4.44.0)
Requirement already satisfied: webdriver-manager in /usr/local/lib/python3.12/dist-packages (4.1.1)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: xlrd in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: certifi>=2026.2.25 in /usr/local/lib/python3.12/dist-packages (from selenium) (2026.4.22)
Requirement already satisfied: trio<1.0,>=0.31.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (0.33.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in /usr/local/lib/python3.12/dist-packages (from selenium) (0.12.2)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (4.15.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.7.0)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (1.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from webdriver-manager) (2.32.4)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (from webdriver-manager) (1.2.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from webdriver-manager) (26.1)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (26.1.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (3.13)
Requirement already satisfied: outcome in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.12/dist-packages (from trio-websocket<1.0,>=0.12.2->selenium) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->webdriver-manager) (3.4.7)
Requirement already satisfied: h11<1,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)

In [16]:
!apt-get update -qq
!apt-get install -y chromium-chromedriver

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  chromium-chromedriver
0 upgraded, 1 newly installed, 0 to remove and 8 not upgraded.
Need to get 2,308 B of archives.
After this operation, 77.8 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 chromium-chromedriver amd64 1:85.0.4183.83-0ubuntu2.22.04.1 [2,308 B]
Fetched 2,308 B in 0s (70.7 kB/s)
Selecting previously unselected package chromium-chromedriver.
(Reading database ... 118668 files and directories currently installed.)
Preparing to unpack .../chromium-chromedriver_1%3a85.0.4183.83-0ubuntu2.22.04.1_amd64.deb ...
Unpacking chromium-chromedriver (1:85.0.4183.83-0ubuntu2.22.04.1) ...
Setting up chromium-chromedriver (1:85.0.4183.83-0ubuntu2.22.04.1) ...

In [19]:
import pandas as pd
import requests
from io import BytesIO
from tqdm import tqdm

headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/122.0.0.0 Safari/537.36"
    )
}

dataframes = []

for url in tqdm(urls):

    try:

        response = requests.get(
            url,
            headers=headers,
            allow_redirects=True,
            timeout=60
        )

        content = response.content

        filename = url.split("/")[-1]

        if filename.endswith(".xlsx"):

            df = pd.read_excel(
                BytesIO(content),
                engine="openpyxl"
            )

        elif filename.endswith(".xls"):

            df = pd.read_excel(
                BytesIO(content),
                engine="xlrd"
            )

        else:
            print(f"Skipped: {url}")
            continue

        year = None

        if "FY" in filename:
            year = filename.split("FY")[1][:4]

        elif "FMR" in filename:
            year = filename.split("FMR")[1][:4]

        if year and year.isdigit():
            df["year"] = int(year)

        dataframes.append(df)

        print(f"Loaded: {filename} -> {df.shape}")

    except Exception as e:

        print(f"Failed: {url} -> {e}")

  4%|▍         | 1/26 [00:01<00:46,  1.84s/it]

Loaded: FY2026_FMR_50_county.xlsx -> (4764, 16)

  8%|▊         | 2/26 [00:02<00:25,  1.06s/it]

Failed: https://www.huduser.gov/portal/datasets/50thper/FY2025_FMR_50_county.xlsx -> Unable to read workbook: could not read properties from None.
This is most probably because the workbook source files contain some invalid XML.
Please see the exception for more details.

 12%|█▏        | 3/26 [00:02<00:18,  1.27it/s]

Failed: https://www.huduser.gov/portal/datasets/50thper/FY2024_FMR_50_county_revised.xlsx -> Unable to read workbook: could not read properties from None.
This is most probably because the workbook source files contain some invalid XML.
Please see the exception for more details.

 15%|█▌        | 4/26 [00:03<00:14,  1.47it/s]

Failed: https://www.huduser.gov/portal/datasets/50thper/FY2023_FMR_50_county_rev.xlsx -> Unable to read workbook: could not read properties from None.
This is most probably because the workbook source files contain some invalid XML.
Please see the exception for more details.

 19%|█▉        | 5/26 [00:03<00:13,  1.55it/s]

Failed: https://www.huduser.gov/portal/datasets/50thper/FY2022_FMR_50_county_rev.xlsx -> Unable to read workbook: could not read properties from None.
This is most probably because the workbook source files contain some invalid XML.
Please see the exception for more details.

 23%|██▎       | 6/26 [00:04<00:15,  1.26it/s]

Loaded: FY2021_50_County.xlsx -> (4766, 17)

 27%|██▋       | 7/26 [00:06<00:17,  1.06it/s]

Loaded: FY2020_50_County_rev.xlsx -> (4767, 17)

 31%|███       | 8/26 [00:07<00:18,  1.04s/it]

Loaded: FY2019_50_County_rev.xlsx -> (4768, 17)

 35%|███▍      | 9/26 [00:08<00:19,  1.14s/it]

Loaded: FY2018_50_County_rev.xlsx -> (4770, 17)

 38%|███▊      | 10/26 [00:10<00:19,  1.24s/it]

Loaded: FY2017_50_rev.xlsx -> (4769, 18)

 42%|████▏     | 11/26 [00:12<00:22,  1.47s/it]

Loaded: FY2016F_50_RevFinal.xlsx -> (4770, 18)

 46%|████▌     | 12/26 [00:13<00:17,  1.25s/it]

Loaded: FY2015_50_RevFinal.xls -> (4769, 18)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero

 50%|█████     | 13/26 [00:13<00:14,  1.08s/it]

Loaded: FY2014_50_RevFinal.xls -> (4766, 18)

 54%|█████▍    | 14/26 [00:14<00:11,  1.06it/s]

Loaded: FY2013_50_Final.xls -> (4766, 18)

 58%|█████▊    | 15/26 [00:14<00:09,  1.22it/s]

Loaded: FY2012_FMRS_50_County.xls -> (4765, 16)

 62%|██████▏   | 16/26 [00:15<00:07,  1.32it/s]

Loaded: FY2011_50_Final_County.xls -> (4765, 16)

 65%|██████▌   | 17/26 [00:16<00:06,  1.44it/s]

WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
Loaded: FY2010_50_Final.xls -> (4763, 16)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero

 69%|██████▉   | 18/26 [00:16<00:05,  1.38it/s]

Loaded: FY2009_50_Rev_Final.xls -> (4763, 16)

 73%|███████▎  | 19/26 [00:17<00:04,  1.49it/s]

Loaded: FY2008_county_level_50th_r.xls -> (4763, 15)

 77%|███████▋  | 20/26 [00:18<00:03,  1.53it/s]

WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
Loaded: FY2007_County_Level_50th.xls -> (4763, 16)

 81%|████████  | 21/26 [00:18<00:03,  1.59it/s]

Loaded: FY2006_County_Level_50th.xls -> (4763, 16)

 85%|████████▍ | 22/26 [00:19<00:02,  1.73it/s]

WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
Loaded: County_Level_50.xls -> (3244, 14)

 88%|████████▊ | 23/26 [00:19<00:01,  1.85it/s]

WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
Loaded: FMR2004F50_County.xls -> (3265, 15)

 92%|█████████▏| 24/26 [00:20<00:01,  1.89it/s]

WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
Loaded: FY2003_50Rents_County.xls -> (3263, 16)

 96%|█████████▌| 25/26 [00:20<00:00,  2.09it/s]

Loaded: FY2002_50th.xls -> (2680, 9)

100%|██████████| 26/26 [00:20<00:00,  1.25it/s]

Loaded: FY2001_50th.xls -> (2680, 9)

In [20]:
#Overview of Initial Data
dataframes

[      state_code  county_code  county_sub_code             cntyname town_name  \
 0             48           59            99999      Callahan County       NaN
 1             48          253            99999         Jones County       NaN
 2             48          441            99999        Taylor County       NaN
 3             72            3            99999     Aguada Municipio       NaN
 4             72            5            99999  Aguadilla Municipio       NaN
 ...          ...          ...              ...                  ...       ...
 4759          72          141            99999     Utuado Municipio       NaN
 4760          72          147            99999    Vieques Municipio       NaN
 4761          78           10            99999            St. Croix       NaN
 4762          78           20            99999             St. John       NaN
 4763          78           30            99999           St. Thomas       NaN

                        hud_areaname    fips2025  rent_50_0  rent_50_1  \
 0                   Abilene, TX MSA  4805999999       1075       1085
 1                   Abilene, TX MSA  4825399999       1075       1085
 2                   Abilene, TX MSA  4844199999       1075       1085
 3                 Aguadilla, PR MSA  7200399999        505        508
 4                 Aguadilla, PR MSA  7200599999        505        508
 ...                             ...         ...        ...        ...
 4759  Puerto Rico HUD Nonmetro Area  7214199999        434        454
 4760  Puerto Rico HUD Nonmetro Area  7214799999        434        454
 4761           St. Croix Island, VI  7801099999       1106       1113
 4762            St. John Island, VI  7802099999       1760       1771
 4763          St. Thomas Island, VI  7803099999       1119       1299

       rent_50_2  rent_50_3  rent_50_4     hud_area_code  pop2023 state_alpha  \
 0          1358       1759       2115  METRO10180M10180    13869          TX
 1          1358       1759       2115  METRO10180M10180    19758          TX
 2          1358       1759       2115  METRO10180M10180   143029          TX
 3           594        716        796  METRO10380M10380    37998          PR
 4           594        716        796  METRO10380M10380    54752          PR
 ...         ...        ...        ...               ...      ...         ...
 4759        498        693        752  NCNTY72923N72923    28155          PR
 4760        498        693        752  NCNTY72923N72923     8199          PR
 4761       1330       1609       1761  NCNTY78010N78010    53234          VI
 4762       2218       2659       2937  NCNTY78020N78020     4197          VI
 4763       1603       1922       2122  NCNTY78030N78030    51181          VI

       year
 0     2026
 1     2026
 2     2026
 3     2026
 4     2026
 ...    ...
 4759  2026
 4760  2026
 4761  2026
 4762  2026
 4763  2026

 [4764 rows x 16 columns],
         fips2010  rent50_0  rent50_1  rent50_2  rent50_3  rent50_4  state  \
 0     4805999999       761       789      1028      1383      1764     48
 1     4825399999       761       789      1028      1383      1764     48
 2     4844199999       761       789      1028      1383      1764     48
 3     7200399999       401       414       472       602       720     72
 4     7200599999       401       414       472       602       720     72
 ...          ...       ...       ...       ...       ...       ...    ...
 4761  7213399999       386       395       450       599       666     72
 4762  7214799999       386       395       450       599       666     72
 4763  7801099999       926       945      1154      1435      1565     78
 4764  7802099999      1230      1458      1812      2254      2457     78
 4765  7803099999       866      1044      1307      1626      1772     78

              cbsasub21                                areaname21  county  \
 0     METRO10180M10180                           Abilene, TX MSA      59
 1     METRO10180M10180                           Abilene, TX MSA     253
 2     METRO10180M10180                           Abilene, TX MSA     441
 3     METRO10380M10380  Aguadilla-Isabela, PR HUD Metro FMR Area       3
 4     METRO10380M10380  Aguadilla-Isabela, PR HUD Metro FMR Area       5
 ...                ...                                       ...     ...
 4761  NCNTY72923N72923             Puerto Rico HUD Nonmetro Area     133
 4762  NCNTY72923N72923             Puerto Rico HUD Nonmetro Area     147
 4763  NCNTY78010N78010                      St. Croix Island, VI      10
 4764  NCNTY78020N78020                       St. John Island, VI      20
 4765  NCNTY78030N78030                     St. Thomas Island, VI      30

       cousub                cntyname                    name  pop2017  hu2017  \
 0      99999         Callahan County         Callahan County    13660    6637
 1      99999            Jones County            Jones County    19970    7292
 2      99999           Taylor County           Taylor County   135370   56978
 3      99999        Aguada Municipio        Aguada Municipio    39470   17385
 4      99999     Aguadilla Municipio     Aguadilla Municipio    55720   27301
 ...      ...                     ...                     ...      ...     ...
 4761   99999  Santa Isabel Municipio  Santa Isabel Municipio    22475    9417
 4762   99999       Vieques Municipio       Vieques Municipio     8930    5101
 4763   99999               St. Croix               St. Croix    53234   25275
 4764   99999                St. John                St. John     4197    3453
 4765   99999              St. Thomas              St. Thomas    51181   27173

      state_alpha  year
 0             TX  2021
 1             TX  2021
 2             TX  2021
 3             PR  2021
 4             PR  2021
 ...          ...   ...
 4761          PR  2021
 4762          PR  2021
 4763          VI  2021
 4764          VI  2021
 4765          VI  2021

 [4766 rows x 17 columns],
         fips2010  rent50_0  rent50_1  rent50_2  rent50_3  rent50_4  state  \
 0     4805999999       673       699       920      1209      1560     48
 1     4825399999       673       699       920      1209      1560     48
 2     4844199999       673       699       920      1209      1560     48
 3     7200399999       386       397       452       591       713     72
 4     7200599999       386       397       452       591       713     72
 ...          ...       ...       ...       ...       ...       ...    ...
 4762  7213399999       370       373       437       582       656     72
 4763  7214799999       370       373       437       582       656     72
 4764  7801099999       887       905      1105      1377      1497     78
 4765  7802099999      1177      1394      1733      2160      2348     78
 4766  7803099999       829      1000      1251      1559      1695     78

              cbsasub20                                areaname20  county  \
 0     METRO10180M10180                           Abilene, TX MSA      59
 1     METRO10180M10180                           Abilene, TX MSA     253
 2     METRO10180M10180                           Abilene, TX MSA     441
 3     METRO10380M10380  Aguadilla-Isabela, PR HUD Metro FMR Area       3
 4     METRO10380M10380  Aguadilla-Isabela, PR HUD Metro FMR Area       5
 ...                ...                                       ...     ...
 4762  NCNTY72923N72923             Puerto Rico HUD Nonmetro Area     133
 4763  NCNTY72923N72923             Puerto Rico HUD Nonmetro Area     147
 4764  NCNTY78010N78010                      St. Croix Island, VI      10
 4765  NCNTY78020N78020                       St. John Island, VI      20
 4766  NCNTY78030N78030                     St. Thomas Island, VI      30

       cousub                cntyname                    name  pop2017  hu2017  \
 0      99999         Callahan County         Callahan County    13660    6637
 1      99999            Jones County            Jones County    19970    7292
 2      99999           Taylor County           Taylor County   135370   56978
 3      99999        Aguada Municipio        Aguada Municipio    39470   17385
 4      99999     Aguadilla Municipio     Aguadilla Municipio    55720   27301
 ...      ...                     ...                     ...      ...     ...
 4762   99999  Santa Isabel Municipio  Santa Isabel Municipio    22475    9417
 4763   99999       Vieques Municipio       Vieques Municipio     8930    5101
 4764   99999               St. Croix               St. Croix    53234   25275
 4765   99999                St. John                St. John     4197    3453
 4766   99999              St. Thomas              St. Thomas    51181   27173

      state_alpha  year
 0             TX  2020
 1             TX  2020
 2             TX  2020
 3             PR  2020
 4             PR  2020
 ...          ...   ...
 4762          PR  2020
 4763          PR  2020
 4764          VI  2020
 4765          VI  2020
 4766          VI  2020

 [4767 rows x 17 columns],
         fips2010  rent50_0  rent50_1  rent50_2  rent50_3  rent50_4  state  \
 0     4805999999       642       667       882      1142      1467     48
 1     4825399999       642       667       882      1142      1467     48
 2     4844199999       642       667       882      1142      1467     48
 3     7200399999       388       398       456       606       732     72
 4     7200599999       388       398       456       606       732     72
 ...          ...       ...       ...       ...       ...       ...    ...
 4763  7213399999       358       367       444       595       696     72
 4764  7214799999       358       367       444       595       696     72
 4765  7801099999       779       794       970      1215      1311     78
 4766  7802099999      1034      1225      1523      1908      2059     78
 4767  7803099999       744       897      1123      1407      1518     78

              cbsasub19                                areaname19  county  \
 0     METRO10180M10180                           Abilene, TX MSA      59
 1     METRO10180M10180                           Abilene, TX MSA     253
 2     METRO10180M10180                           Abilene, TX MSA     441
 3     METRO10380M10380  Aguadilla-Isabela, PR HUD Metro FMR Area       3
 4     METRO10380M10380  Aguadilla-Isabela, PR HUD Metro FMR Area       5
 ...                ...                                       ...     ...
 4763  NCNTY72923N72923             Puerto Rico HUD Nonmetro Area     133
 4764  NCNTY72923N72923             Puerto Rico HUD Nonmetro Area     147
 4765  NCNTY78010N78010                      St. Croix Island, VI      10
 4766  NCNTY78020N78020                       St. John Island, VI      20
 4767  NCNTY78030N78030                     St. Thomas Island, VI      30

       cousub                cntyname                    name  pop2010  hu2010  \
 0      99999         Callahan County         Callahan County    13544    6549
 1      99999            Jones County            Jones County    20202    7422
 2      99999           Taylor County           Taylor County   131506   55750
 3      99999        Aguada Municipio        Aguada Municipio    41959   18258
 4      99999     Aguadilla Municipio     Aguadilla Municipio    60949   28430
 ...      ...                     ...                     ...      ...     ...
 4763   99999  Santa Isabel Municipio  Santa Isabel Municipio    23274    9575
 4764   99999       Vieques Municipio       Vieques Municipio     9301    5541
 4765   99999               St. Croix               St. Croix    53234   25275
 4766   99999                St. John                St. John     4197    3453
 4767   99999              St. Thomas              St. Thomas    51181   27173

      state_alpha  year
 0             TX  2019
 1             TX  2019
 2             TX  2019
 3             PR  2019
 4             PR  2019
 ...          ...   ...
 4763          PR  2019
 4764          PR  2019
 4765          VI  2019
 4766          VI  2019
 4767          VI  2019

 [4768 rows x 17 columns],
         fips2010  rent50_0  rent50_1  rent50_2  rent50_3  rent50_4  state  \
 0      100199999       631       742       890      1133      1558      1
 1      100399999       786       809       929      1351      1578      1
 2      100599999       527       531       706       885       998      1
 3      100799999       749       832       955      1273      1424      1
 4      100999999       749       832       955      1273      1424      1
 ...          ...       ...       ...       ...       ...       ...    ...
 4765  7215199999       452       478       577       769       961     72
 4766  7215399999       330       340       390       511       687     72
 4767  7801099999       816       833      1017      1275      1385     78
 4768  7802099999      1084      1284      1596      2001      2174     78
 4769  7803099999       763       921      1152      1444      1569     78

              cbsasub18                                areaname18  county  \
 0     METRO33860M33860                        Montgomery, AL MSA       1
 1     METRO19300M19300             Daphne-Fairhope-Foley, AL MSA       3
 2     NCNTY01005N01005                        Barbour County, AL       5
 3     METRO13820M13820  Birmingham-Hoover, AL HUD Metro FMR Area       7
 4     METRO13820M13820  Birmingham-Hoover, AL HUD Metro FMR Area       9
 ...                ...                                       ...     ...
 4765  METRO41980MM7440  San Juan-Guaynabo, PR HUD Metro FMR Area     151
 4766  METRO38660M49500              Yauco, PR HUD Metro FMR Area     153
 4767  NCNTY78010N78010                      St. Croix Island, VI      10
 4768  NCNTY78020N78020                       St. John Island, VI      20
 4769  NCNTY78030N78030                     St. Thomas Island, VI      30

       cousub           cntyname               name   pop2010    hu2010  \
 0      99999     Autauga County     Autauga County   54571.0   22135.0
 1      99999     Baldwin County     Baldwin County  182265.0  104061.0
 2      99999     Barbour County     Barbour County   27457.0   11829.0
 3      99999        Bibb County        Bibb County   22915.0    8981.0
 4      99999      Blount County      Blount County   57322.0   23887.0
 ...      ...                ...                ...       ...       ...
 4765   99999  Yabucoa Municipio  Yabucoa Municipio   37941.0   15798.0
 4766   99999    Yauco Municipio    Yauco Municipio   42043.0   18020.0
 4767   99999          St. Croix          St. Croix   53234.0   25275.0
 4768   99999           St. John           St. John    4197.0    3453.0
 4769   99999         St. Thomas         St. Thomas   51181.0   27173.0

      state_alpha  year
 0             AL  2018
 1             AL  2018
 2             AL  2018
 3             AL  2018
 4             AL  2018
 ...          ...   ...
 4765          PR  2018
 4766          PR  2018
 4767          VI  2018
 4768          VI  2018
 4769          VI  2018

 [4770 rows x 17 columns],
         fips2010      fips2000  Rent50_2  Rent50_0  Rent50_1  Rent50_3  \
 0      100199999  1.002000e+08       886       633       735      1136
 1      100399999  1.004000e+08      1047       865       908      1524
 2      100599999  1.006000e+08       722       540       543       903
 3      100799999  1.008000e+08       937       719       812      1258
 4      100999999  1.010000e+08       937       719       812      1258
 ...          ...           ...       ...       ...       ...       ...
 4764  7215199999  7.215200e+09       605       471       502       813
 4765  7215399999  7.215400e+09       432       357       374       555
 4766  7801099999  7.801100e+09       952       764       780      1181
 4767  7802099999  7.802100e+09      1529      1038      1230      1897
 4768  7803099999  7.803100e+09      1093       724       873      1356

       Rent50_4  State           cbsasub  \
 0         1536      1  METRO33860M33860
 1         1751      1  METRO19300M19300
 2         1031      1  NCNTY01005N01005
 3         1405      1  METRO13820M13820
 4         1405      1  METRO13820M13820
 ...        ...    ...               ...
 4764      1011     72  METRO41980MM7440
 4765       761     72  METRO38660M49500
 4766      1305     78  NCNTY78010N78010
 4767      2096     78  NCNTY78020N78020
 4768      1498     78  NCNTY78030N78030

                                       areaname  county  CouSub  \
 0                           Montgomery, AL MSA     1.0   99999
 1                Daphne-Fairhope-Foley, AL MSA     3.0   99999
 2                           Barbour County, AL     5.0   99999
 3     Birmingham-Hoover, AL HUD Metro FMR Area     7.0   99999
 4     Birmingham-Hoover, AL HUD Metro FMR Area     9.0   99999
 ...                                        ...     ...     ...
 4764  San Juan-Guaynabo, PR HUD Metro FMR Area   151.0   99999
 4765              Yauco, PR HUD Metro FMR Area   153.0   99999
 4766                      St. Croix Island, VI    10.0   99999
 4767                       St. John Island, VI    20.0   99999
 4768                     St. Thomas Island, VI    30.0   99999

              countyname   county_town_name   pop2010    hu2010 state_alpha  \
 0        Autauga County     Autauga County   54571.0   22135.0          AL
 1        Baldwin County     Baldwin County  182265.0  104061.0          AL
 2        Barbour County     Barbour County   27457.0   11829.0          AL
 3           Bibb County        Bibb County   22915.0    8981.0          AL
 4         Blount County      Blount County   57322.0   23887.0          AL
 ...                 ...                ...       ...       ...         ...
 4764  Yabucoa Municipio  Yabucoa Municipio   37941.0   15798.0          PR
 4765    Yauco Municipio    Yauco Municipio   42043.0   18020.0          PR
 4766          St. Croix          St. Croix   53234.0   25275.0          VI
 4767           St. John           St. John    4197.0    3453.0          VI
 4768         St. Thomas         St. Thomas   51181.0   27173.0          VI

       year
 0     2017
 1     2017
 2     2017
 3     2017
 4     2017
 ...    ...
 4764  2017
 4765  2017
 4766  2017
 4767  2017
 4768  2017

 [4769 rows x 18 columns],
           fips2000    fips2010  Rent50_2  Rent50_0  Rent50_1  Rent50_3  \
 0     1.002000e+08   100199999       840       602       690      1097
 1     1.004000e+08   100399999       935       770       808      1363
 2     1.006000e+08   100599999       678       503       507       841
 3     1.008000e+08   100799999       914       666       790      1234
 4     1.010000e+08   100999999       914       666       790      1234
 ...            ...         ...       ...       ...       ...       ...
 4765  7.215200e+09  7215199999       600       446       499       806
 4766  7.215400e+09  7215399999       428       352       353       551
 4767  7.801100e+09  7801099999       926       743       758      1149
 4768  7.802100e+09  7802099999      1488      1010      1197      1846
 4769  7.803100e+09  7803099999      1063       704       849      1319

       Rent50_4  State           cbsasub  \
 0         1424      1  METRO33860M33860
 1         1577      1  METRO19300M19300
 2          929      1  NCNTY01005N01005
 3         1360      1  METRO13820M13820
 4         1360      1  METRO13820M13820
 ...        ...    ...               ...
 4765       980     72  METRO41980MM7440
 4766       747     72  METRO38660M49500
 4767      1269     78  NCNTY78010N78010
 4768      2040     78  NCNTY78020N78020
 4769      1457     78  NCNTY78030N78030

                                       areaname  county  CouSub  \
 0                           Montgomery, AL MSA     1.0   99999
 1                Daphne-Fairhope-Foley, AL MSA     3.0   99999
 2                           Barbour County, AL     5.0   99999

In [25]:
import zipfile
import xml.etree.ElementTree as ET
import pandas as pd

def load_problematic_xlsx(path):

    with zipfile.ZipFile(path) as z:

        shared_strings = []

        if "xl/sharedStrings.xml" in z.namelist():

            root = ET.fromstring(z.read("xl/sharedStrings.xml"))

            ns = {
                "main":
                "http://schemas.openxmlformats.org/spreadsheetml/2006/main"
            }

            for si in root.findall(".//main:t", ns):
                shared_strings.append(si.text)

        sheet = "xl/worksheets/sheet1.xml"

        root = ET.fromstring(z.read(sheet))

        ns = {
            "main":
            "http://schemas.openxmlformats.org/spreadsheetml/2006/main"
        }

        rows = []

        for row in root.findall(".//main:row", ns):

            vals = []

            for c in row.findall("main:c", ns):

                v = c.find("main:v", ns)

                if v is not None:

                    val = v.text

                    if c.attrib.get("t") == "s":
                        val = shared_strings[int(val)]

                    vals.append(val)

                else:
                    vals.append(None)

            rows.append(vals)

    df = pd.DataFrame(rows)

    df.columns = df.iloc[0]

    df = df[1:].reset_index(drop=True)

    return df

In [26]:
import pandas as pd

files = [
    "FY2025_FMR_50_county.xlsx",
    "FY2024_FMR_50_county_revised.xlsx",
    "FY2023_FMR_50_county_rev.xlsx",
    "FY2022_FMR_50_county_rev.xlsx"
]

problematic_dataframes = []

for file in files:

    try:
        df = load_problematic_xlsx(file)

        year = int(file.split("FY")[1][:4])

        df["year"] = year

        problematic_dataframes.append(df)

        print(f"{file} -> Loaded: {df.shape}")

    except Exception as e:
        print(f"{file} -> Failed: {e}")

FY2025_FMR_50_county.xlsx -> Loaded: (4764, 16)
FY2024_FMR_50_county_revised.xlsx -> Loaded: (4764, 16)
FY2023_FMR_50_county_rev.xlsx -> Loaded: (4764, 16)
FY2022_FMR_50_county_rev.xlsx -> Loaded: (4765, 14)

In [27]:
problematic_dataframes

[0    state_code county_code county_sub_code                cntyname town_name  \
 0            48         059           99999         Callahan County      None
 1            48         253           99999            Jones County      None
 2            48         441           99999           Taylor County      None
 3            72         003           99999        Aguada Municipio      None
 4            72         005           99999     Aguadilla Municipio      None
 ...         ...         ...             ...                     ...       ...
 4759         72         133           99999  Santa Isabel Municipio      None
 4760         72         147           99999       Vieques Municipio      None
 4761         78         010           99999               St. Croix      None
 4762         78         020           99999                St. John      None
 4763         78         030           99999              St. Thomas      None

 0                      hud_areaname    fips2010 rent_50_0 rent_50_1 rent_50_2  \
 0                   Abilene, TX MSA  4805999999      1006      1013      1287
 1                   Abilene, TX MSA  4825399999      1006      1013      1287
 2                   Abilene, TX MSA  4844199999      1006      1013      1287
 3         Aguadilla-Isabela, PR MSA  7200399999       515       518       592
 4         Aguadilla-Isabela, PR MSA  7200599999       515       518       592
 ...                             ...         ...       ...       ...       ...
 4759  Puerto Rico HUD Nonmetro Area  7213399999       436       452       501
 4760  Puerto Rico HUD Nonmetro Area  7214799999       436       452       501
 4761           St. Croix Island, VI  7801099999      1235      1260      1539
 4762            St. John Island, VI  7802099999      1656      1943      2415
 4763          St. Thomas Island, VI  7803099999      1195      1393      1743

 0    rent_50_3 rent_50_4     hud_area_code pop2020 state_alpha  year
 0         1675      2025  METRO10180M10180   13959          TX  2025
 1         1675      2025  METRO10180M10180   19874          TX  2025
 2         1675      2025  METRO10180M10180  137521          TX  2025
 3          720       802  METRO10380M10380   37307          PR  2025
 4          720       802  METRO10380M10380   51552          PR  2025
 ...        ...       ...               ...     ...         ...   ...
 4759       702       773  NCNTY72923N72923   21474          PR  2025
 4760       702       773  NCNTY72923N72923    8508          PR  2025
 4761      1854      2040  NCNTY78010N78010   53234          VI  2025
 4762      2910      3202  NCNTY78020N78020    4197          VI  2025
 4763      2100      2311  NCNTY78030N78030   51181          VI  2025

 [4764 rows x 16 columns],
 0    state_code county_code county_sub_code                cntyname town_name  \
 0            48         059           99999         Callahan County      None
 1            48         253           99999            Jones County      None
 2            48         441           99999           Taylor County      None
 3            72         003           99999        Aguada Municipio      None
 4            72         005           99999     Aguadilla Municipio      None
 ...         ...         ...             ...                     ...       ...
 4759         72         133           99999  Santa Isabel Municipio      None
 4760         72         147           99999       Vieques Municipio      None
 4761         78         010           99999               St. Croix      None
 4762         78         020           99999                St. John      None
 4763         78         030           99999              St. Thomas      None

 0                      hud_areaname    fips2010 rent_50_0 rent_50_1 rent_50_2  \
 0                   Abilene, TX MSA  4805999999       894       910      1160
 1                   Abilene, TX MSA  4825399999       894       910      1160
 2                   Abilene, TX MSA  4844199999       894       910      1160
 3         Aguadilla-Isabela, PR MSA  7200399999       480       484       554
 4         Aguadilla-Isabela, PR MSA  7200599999       480       484       554
 ...                             ...         ...       ...       ...       ...
 4759  Puerto Rico HUD Nonmetro Area  7213399999       434       446       501
 4760  Puerto Rico HUD Nonmetro Area  7214799999       434       446       501
 4761           St. Croix Island, VI  7801099999      1203      1228      1499
 4762            St. John Island, VI  7802099999      1597      1893      2352
 4763          St. Thomas Island, VI  7803099999      1151      1357      1698

 0    rent_50_3 rent_50_4     hud_area_code pop2020 state_alpha  year
 0         1545      1857  METRO10180M10180   13959          TX  2024
 1         1545      1857  METRO10180M10180   19874          TX  2024
 2         1545      1857  METRO10180M10180  137521          TX  2024
 3          674       761  METRO10380M10380   37307          PR  2024
 4          674       761  METRO10380M10380   51552          PR  2024
 ...        ...       ...               ...     ...         ...   ...
 4759       706       780  NCNTY72923N72923   21474          PR  2024
 4760       706       780  NCNTY72923N72923    8508          PR  2024
 4761      1812      1996  NCNTY78010N78010   53234          VI  2024
 4762      2844      3132  NCNTY78020N78020    4197          VI  2024
 4763      2053      2261  NCNTY78030N78030   51181          VI  2024

 [4764 rows x 16 columns],
 0    state_code county_code county_sub_code                cntyname town_name  \
 0            48         059           99999         Callahan County      None
 1            48         253           99999            Jones County      None
 2            48         441           99999           Taylor County      None
 3            72         003           99999        Aguada Municipio      None
 4            72         005           99999     Aguadilla Municipio      None
 ...         ...         ...             ...                     ...       ...
 4759         72         133           99999  Santa Isabel Municipio      None
 4760         72         147           99999       Vieques Municipio      None
 4761         78         010           99999               St. Croix      None
 4762         78         020           99999                St. John      None
 4763         78         030           99999              St. Thomas      None

 0                      hud_areaname    fips2010 rent_50_0 rent_50_1 rent_50_2  \
 0                   Abilene, TX MSA  4805999999       760       808      1044
 1                   Abilene, TX MSA  4825399999       760       808      1044
 2                   Abilene, TX MSA  4844199999       760       808      1044
 3         Aguadilla-Isabela, PR MSA  7200399999       405       444       512
 4         Aguadilla-Isabela, PR MSA  7200599999       405       444       512
 ...                             ...         ...       ...       ...       ...
 4759  Puerto Rico HUD Nonmetro Area  7213399999       411       421       475
 4760  Puerto Rico HUD Nonmetro Area  7214799999       411       421       475
 4761           St. Croix Island, VI  7801099999      1038      1059      1293
 4762            St. John Island, VI  7802099999      1378      1633      2029
 4763          St. Thomas Island, VI  7803099999       980      1171      1465

 0    rent_50_3 rent_50_4     hud_area_code pop2020 state_alpha  year
 0         1412      1711  METRO10180M10180   13959          TX  2023
 1         1412      1711  METRO10180M10180   19874          TX  2023
 2         1412      1711  METRO10180M10180  137521          TX  2023
 3          630       714  METRO10380M10380   37307          PR  2023
 4          630       714  METRO10380M10380   51552          PR  2023
 ...        ...       ...               ...     ...         ...   ...
 4759       659       728  NCNTY72923N72923   21474          PR  2023
 4760       659       728  NCNTY72923N72923    8508          PR  2023
 4761      1574      1737  NCNTY78010N78010   53234          VI  2023
 4762      2469      2726  NCNTY78020N78020    4197          VI  2023
 4763      1783      1968  NCNTY78030N78030   51181          VI  2023

 [4764 rows x 16 columns],
 0    state_code county_code county_sub_code                cntyname town_name  \
 0            48         059           99999         Callahan County      None
 1            48         253           99999            Jones County      None
 2            48         441           99999           Taylor County      None
 3            72         003           99999        Aguada Municipio      None
 4            72         005           99999     Aguadilla Municipio      None
 ...         ...         ...             ...                     ...       ...
 4760         72         133           99999  Santa Isabel Municipio      None
 4761         72         147           99999       Vieques Municipio      None
 4762         78         010           99999               St. Croix      None
 4763         78         020           99999                St. John      None
 4764         78         030           99999              St. Thomas      None

 0                        areaname22 rent_50_0 rent_50_1 rent_50_2 rent_50_3  \
 0                   Abilene, TX MSA       715       760       981      1337
 1                   Abilene, TX MSA       715       760       981      1337
 2                   Abilene, TX MSA       715       760       981      1337
 3         Aguadilla-Isabela, PR MSA       407       423       486       604
 4         Aguadilla-Isabela, PR MSA       407       423       486       604
 ...                             ...       ...       ...       ...       ...
 4760  Puerto Rico HUD Nonmetro Area       389       396       451       614
 4761  Puerto Rico HUD Nonmetro Area       389       396       451       614
 4762           St. Croix Island, VI       964       984      1201      1485
 4763            St. John Island, VI      1280      1517      1885      2330
 4764          St. Thomas Island, VI       904      1088      1361      1682

 0    rent_50_4         cbsasub22 pop2017  year
 0         1658  METRO10180M10180   13660  2022
 1         1658  METRO10180M10180   19970  2022
 2         1658  METRO10180M10180  135370  2022
 3          711  METRO10380M10380   39470  2022
 4          711  METRO10380M10380   55720  2022
 ...        ...               ...     ...   ...
 4760       674  NCNTY72923N72923   22475  2022
 4761       674  NCNTY72923N72923    8930  2022
 4762      1629  NCNTY78010N78010   53234  2022
 4763      2556  NCNTY78020N78020    4197  2022
 4764      1846  NCNTY78030N78030   51181  2022

 [4765 rows x 14 columns]]

### Combining all Dataframes into 1 Dataframe

In [28]:
# Combining the two lists
combined_list = dataframes + problematic_dataframes
combined_list

[      state_code  county_code  county_sub_code             cntyname town_name  \
 0             48           59            99999      Callahan County       NaN
 1             48          253            99999         Jones County       NaN
 2             48          441            99999        Taylor County       NaN
 3             72            3            99999     Aguada Municipio       NaN
 4             72            5            99999  Aguadilla Municipio       NaN
 ...          ...          ...              ...                  ...       ...
 4759          72          141            99999     Utuado Municipio       NaN
 4760          72          147            99999    Vieques Municipio       NaN
 4761          78           10            99999            St. Croix       NaN
 4762          78           20            99999             St. John       NaN
 4763          78           30            99999           St. Thomas       NaN

                        hud_areaname    fips2025  rent_50_0  rent_50_1  \
 0                   Abilene, TX MSA  4805999999       1075       1085
 1                   Abilene, TX MSA  4825399999       1075       1085
 2                   Abilene, TX MSA  4844199999       1075       1085
 3                 Aguadilla, PR MSA  7200399999        505        508
 4                 Aguadilla, PR MSA  7200599999        505        508
 ...                             ...         ...        ...        ...
 4759  Puerto Rico HUD Nonmetro Area  7214199999        434        454
 4760  Puerto Rico HUD Nonmetro Area  7214799999        434        454
 4761           St. Croix Island, VI  7801099999       1106       1113
 4762            St. John Island, VI  7802099999       1760       1771
 4763          St. Thomas Island, VI  7803099999       1119       1299

       rent_50_2  rent_50_3  rent_50_4     hud_area_code  pop2023 state_alpha  \
 0          1358       1759       2115  METRO10180M10180    13869          TX
 1          1358       1759       2115  METRO10180M10180    19758          TX
 2          1358       1759       2115  METRO10180M10180   143029          TX
 3           594        716        796  METRO10380M10380    37998          PR
 4           594        716        796  METRO10380M10380    54752          PR
 ...         ...        ...        ...               ...      ...         ...
 4759        498        693        752  NCNTY72923N72923    28155          PR
 4760        498        693        752  NCNTY72923N72923     8199          PR
 4761       1330       1609       1761  NCNTY78010N78010    53234          VI
 4762       2218       2659       2937  NCNTY78020N78020     4197          VI
 4763       1603       1922       2122  NCNTY78030N78030    51181          VI

       year
 0     2026
 1     2026
 2     2026
 3     2026
 4     2026
 ...    ...
 4759  2026
 4760  2026
 4761  2026
 4762  2026
 4763  2026

 [4764 rows x 16 columns],
         fips2010  rent50_0  rent50_1  rent50_2  rent50_3  rent50_4  state  \
 0     4805999999       761       789      1028      1383      1764     48
 1     4825399999       761       789      1028      1383      1764     48
 2     4844199999       761       789      1028      1383      1764     48
 3     7200399999       401       414       472       602       720     72
 4     7200599999       401       414       472       602       720     72
 ...          ...       ...       ...       ...       ...       ...    ...
 4761  7213399999       386       395       450       599       666     72
 4762  7214799999       386       395       450       599       666     72
 4763  7801099999       926       945      1154      1435      1565     78
 4764  7802099999      1230      1458      1812      2254      2457     78
 4765  7803099999       866      1044      1307      1626      1772     78

              cbsasub21                                areaname21  county  \
 0     METRO10180M10180                           Abilene, TX MSA      59
 1     METRO10180M10180                           Abilene, TX MSA     253
 2     METRO10180M10180                           Abilene, TX MSA     441
 3     METRO10380M10380  Aguadilla-Isabela, PR HUD Metro FMR Area       3
 4     METRO10380M10380  Aguadilla-Isabela, PR HUD Metro FMR Area       5
 ...                ...                                       ...     ...
 4761  NCNTY72923N72923             Puerto Rico HUD Nonmetro Area     133
 4762  NCNTY72923N72923             Puerto Rico HUD Nonmetro Area     147
 4763  NCNTY78010N78010                      St. Croix Island, VI      10
 4764  NCNTY78020N78020                       St. John Island, VI      20
 4765  NCNTY78030N78030                     St. Thomas Island, VI      30

       cousub                cntyname                    name  pop2017  hu2017  \
 0      99999         Callahan County         Callahan County    13660    6637
 1      99999            Jones County            Jones County    19970    7292
 2      99999           Taylor County           Taylor County   135370   56978
 3      99999        Aguada Municipio        Aguada Municipio    39470   17385
 4      99999     Aguadilla Municipio     Aguadilla Municipio    55720   27301
 ...      ...                     ...                     ...      ...     ...
 4761   99999  Santa Isabel Municipio  Santa Isabel Municipio    22475    9417
 4762   99999       Vieques Municipio       Vieques Municipio     8930    5101
 4763   99999               St. Croix               St. Croix    53234   25275
 4764   99999                St. John                St. John     4197    3453
 4765   99999              St. Thomas              St. Thomas    51181   27173

      state_alpha  year
 0             TX  2021
 1             TX  2021
 2             TX  2021
 3             PR  2021
 4             PR  2021
 ...          ...   ...
 4761          PR  2021
 4762          PR  2021
 4763          VI  2021
 4764          VI  2021
 4765          VI  2021

 [4766 rows x 17 columns],
         fips2010  rent50_0  rent50_1  rent50_2  rent50_3  rent50_4  state  \
 0     4805999999       673       699       920      1209      1560     48
 1     4825399999       673       699       920      1209      1560     48
 2     4844199999       673       699       920      1209      1560     48
 3     7200399999       386       397       452       591       713     72
 4     7200599999       386       397       452       591       713     72
 ...          ...       ...       ...       ...       ...       ...    ...
 4762  7213399999       370       373       437       582       656     72
 4763  7214799999       370       373       437       582       656     72
 4764  7801099999       887       905      1105      1377      1497     78
 4765  7802099999      1177      1394      1733      2160      2348     78
 4766  7803099999       829      1000      1251      1559      1695     78

              cbsasub20                                areaname20  county  \
 0     METRO10180M10180                           Abilene, TX MSA      59
 1     METRO10180M10180                           Abilene, TX MSA     253
 2     METRO10180M10180                           Abilene, TX MSA     441
 3     METRO10380M10380  Aguadilla-Isabela, PR HUD Metro FMR Area       3
 4     METRO10380M10380  Aguadilla-Isabela, PR HUD Metro FMR Area       5
 ...                ...                                       ...     ...
 4762  NCNTY72923N72923             Puerto Rico HUD Nonmetro Area     133
 4763  NCNTY72923N72923             Puerto Rico HUD Nonmetro Area     147
 4764  NCNTY78010N78010                      St. Croix Island, VI      10
 4765  NCNTY78020N78020                       St. John Island, VI      20
 4766  NCNTY78030N78030                     St. Thomas Island, VI      30

       cousub                cntyname                    name  pop2017  hu2017  \
 0      99999         Callahan County         Callahan County    13660    6637
 1      99999            Jones County            Jones County    19970    7292
 2      99999           Taylor County           Taylor County   135370   56978
 3      99999        Aguada Municipio        Aguada Municipio    39470   17385
 4      99999     Aguadilla Municipio     Aguadilla Municipio    55720   27301
 ...      ...                     ...                     ...      ...     ...
 4762   99999  Santa Isabel Municipio  Santa Isabel Municipio    22475    9417
 4763   99999       Vieques Municipio       Vieques Municipio     8930    5101
 4764   99999               St. Croix               St. Croix    53234   25275
 4765   99999                St. John                St. John     4197    3453
 4766   99999              St. Thomas              St. Thomas    51181   27173

      state_alpha  year
 0             TX  2020
 1             TX  2020
 2             TX  2020
 3             PR  2020
 4             PR  2020
 ...          ...   ...
 4762          PR  2020
 4763          PR  2020
 4764          VI  2020
 4765          VI  2020
 4766          VI  2020

 [4767 rows x 17 columns],
         fips2010  rent50_0  rent50_1  rent50_2  rent50_3  rent50_4  state  \
 0     4805999999       642       667       882      1142      1467     48
 1     4825399999       642       667       882      1142      1467     48
 2     4844199999       642       667       882      1142      1467     48
 3     7200399999       388       398       456       606       732     72
 4     7200599999       388       398       456       606       732     72
 ...          ...       ...       ...       ...       ...       ...    ...
 4763  7213399999       358       367       444       595       696     72
 4764  7214799999       358       367       444       595       696     72
 4765  7801099999       779       794       970      1215      1311     78
 4766  7802099999      1034      1225      1523      1908      2059     78
 4767  7803099999       744       897      1123      1407      1518     78

              cbsasub19                                areaname19  county  \
 0     METRO10180M10180                           Abilene, TX MSA      59
 1     METRO10180M10180                           Abilene, TX MSA     253
 2     METRO10180M10180                           Abilene, TX MSA     441
 3     METRO10380M10380  Aguadilla-Isabela, PR HUD Metro FMR Area       3
 4     METRO10380M10380  Aguadilla-Isabela, PR HUD Metro FMR Area       5
 ...                ...                                       ...     ...
 4763  NCNTY72923N72923             Puerto Rico HUD Nonmetro Area     133
 4764  NCNTY72923N72923             Puerto Rico HUD Nonmetro Area     147
 4765  NCNTY78010N78010                      St. Croix Island, VI      10
 4766  NCNTY78020N78020                       St. John Island, VI      20
 4767  NCNTY78030N78030                     St. Thomas Island, VI      30

       cousub                cntyname                    name  pop2010  hu2010  \
 0      99999         Callahan County         Callahan County    13544    6549
 1      99999            Jones County            Jones County    20202    7422
 2      99999           Taylor County           Taylor County   131506   55750
 3      99999        Aguada Municipio        Aguada Municipio    41959   18258
 4      99999     Aguadilla Municipio     Aguadilla Municipio    60949   28430
 ...      ...                     ...                     ...      ...     ...
 4763   99999  Santa Isabel Municipio  Santa Isabel Municipio    23274    9575
 4764   99999       Vieques Municipio       Vieques Municipio     9301    5541
 4765   99999               St. Croix               St. Croix    53234   25275
 4766   99999                St. John                St. John     4197    3453
 4767   99999              St. Thomas              St. Thomas    51181   27173

      state_alpha  year
 0             TX  2019
 1             TX  2019
 2             TX  2019
 3             PR  2019
 4             PR  2019
 ...          ...   ...
 4763          PR  2019
 4764          PR  2019
 4765          VI  2019
 4766          VI  2019
 4767          VI  2019

 [4768 rows x 17 columns],
         fips2010  rent50_0  rent50_1  rent50_2  rent50_3  rent50_4  state  \
 0      100199999       631       742       890      1133      1558      1
 1      100399999       786       809       929      1351      1578      1
 2      100599999       527       531       706       885       998      1
 3      100799999       749       832       955      1273      1424      1
 4      100999999       749       832       955      1273      1424      1
 ...          ...       ...       ...       ...       ...       ...    ...
 4765  7215199999       452       478       577       769       961     72
 4766  7215399999       330       340       390       511       687     72
 4767  7801099999       816       833      1017      1275      1385     78
 4768  7802099999      1084      1284      1596      2001      2174     78
 4769  7803099999       763       921      1152      1444      1569     78

              cbsasub18                                areaname18  county  \
 0     METRO33860M33860                        Montgomery, AL MSA       1
 1     METRO19300M19300             Daphne-Fairhope-Foley, AL MSA       3
 2     NCNTY01005N01005                        Barbour County, AL       5
 3     METRO13820M13820  Birmingham-Hoover, AL HUD Metro FMR Area       7
 4     METRO13820M13820  Birmingham-Hoover, AL HUD Metro FMR Area       9
 ...                ...                                       ...     ...
 4765  METRO41980MM7440  San Juan-Guaynabo, PR HUD Metro FMR Area     151
 4766  METRO38660M49500              Yauco, PR HUD Metro FMR Area     153
 4767  NCNTY78010N78010                      St. Croix Island, VI      10
 4768  NCNTY78020N78020                       St. John Island, VI      20
 4769  NCNTY78030N78030                     St. Thomas Island, VI      30

       cousub           cntyname               name   pop2010    hu2010  \
 0      99999     Autauga County     Autauga County   54571.0   22135.0
 1      99999     Baldwin County     Baldwin County  182265.0  104061.0
 2      99999     Barbour County     Barbour County   27457.0   11829.0
 3      99999        Bibb County        Bibb County   22915.0    8981.0
 4      99999      Blount County      Blount County   57322.0   23887.0
 ...      ...                ...                ...       ...       ...
 4765   99999  Yabucoa Municipio  Yabucoa Municipio   37941.0   15798.0
 4766   99999    Yauco Municipio    Yauco Municipio   42043.0   18020.0
 4767   99999          St. Croix          St. Croix   53234.0   25275.0
 4768   99999           St. John           St. John    4197.0    3453.0
 4769   99999         St. Thomas         St. Thomas   51181.0   27173.0

      state_alpha  year
 0             AL  2018
 1             AL  2018
 2             AL  2018
 3             AL  2018
 4             AL  2018
 ...          ...   ...
 4765          PR  2018
 4766          PR  2018
 4767          VI  2018
 4768          VI  2018
 4769          VI  2018

 [4770 rows x 17 columns],
         fips2010      fips2000  Rent50_2  Rent50_0  Rent50_1  Rent50_3  \
 0      100199999  1.002000e+08       886       633       735      1136
 1      100399999  1.004000e+08      1047       865       908      1524
 2      100599999  1.006000e+08       722       540       543       903
 3      100799999  1.008000e+08       937       719       812      1258
 4      100999999  1.010000e+08       937       719       812      1258
 ...          ...           ...       ...       ...       ...       ...
 4764  7215199999  7.215200e+09       605       471       502       813
 4765  7215399999  7.215400e+09       432       357       374       555
 4766  7801099999  7.801100e+09       952       764       780      1181
 4767  7802099999  7.802100e+09      1529      1038      1230      1897
 4768  7803099999  7.803100e+09      1093       724       873      1356

       Rent50_4  State           cbsasub  \
 0         1536      1  METRO33860M33860
 1         1751      1  METRO19300M19300
 2         1031      1  NCNTY01005N01005
 3         1405      1  METRO13820M13820
 4         1405      1  METRO13820M13820
 ...        ...    ...               ...
 4764      1011     72  METRO41980MM7440
 4765       761     72  METRO38660M49500
 4766      1305     78  NCNTY78010N78010
 4767      2096     78  NCNTY78020N78020
 4768      1498     78  NCNTY78030N78030

                                       areaname  county  CouSub  \
 0                           Montgomery, AL MSA     1.0   99999
 1                Daphne-Fairhope-Foley, AL MSA     3.0   99999
 2                           Barbour County, AL     5.0   99999
 3     Birmingham-Hoover, AL HUD Metro FMR Area     7.0   99999
 4     Birmingham-Hoover, AL HUD Metro FMR Area     9.0   99999
 ...                                        ...     ...     ...
 4764  San Juan-Guaynabo, PR HUD Metro FMR Area   151.0   99999
 4765              Yauco, PR HUD Metro FMR Area   153.0   99999
 4766                      St. Croix Island, VI    10.0   99999
 4767                       St. John Island, VI    20.0   99999
 4768                     St. Thomas Island, VI    30.0   99999

              countyname   county_town_name   pop2010    hu2010 state_alpha  \
 0        Autauga County     Autauga County   54571.0   22135.0          AL
 1        Baldwin County     Baldwin County  182265.0  104061.0          AL
 2        Barbour County     Barbour County   27457.0   11829.0          AL
 3           Bibb County        Bibb County   22915.0    8981.0          AL
 4         Blount County      Blount County   57322.0   23887.0          AL
 ...                 ...                ...       ...       ...         ...
 4764  Yabucoa Municipio  Yabucoa Municipio   37941.0   15798.0          PR
 4765    Yauco Municipio    Yauco Municipio   42043.0   18020.0          PR
 4766          St. Croix          St. Croix   53234.0   25275.0          VI
 4767           St. John           St. John    4197.0    3453.0          VI
 4768         St. Thomas         St. Thomas   51181.0   27173.0          VI

       year
 0     2017
 1     2017
 2     2017
 3     2017
 4     2017
 ...    ...
 4764  2017
 4765  2017
 4766  2017
 4767  2017
 4768  2017

 [4769 rows x 18 columns],
           fips2000    fips2010  Rent50_2  Rent50_0  Rent50_1  Rent50_3  \
 0     1.002000e+08   100199999       840       602       690      1097
 1     1.004000e+08   100399999       935       770       808      1363
 2     1.006000e+08   100599999       678       503       507       841
 3     1.008000e+08   100799999       914       666       790      1234
 4     1.010000e+08   100999999       914       666       790      1234
 ...            ...         ...       ...       ...       ...       ...
 4765  7.215200e+09  7215199999       600       446       499       806
 4766  7.215400e+09  7215399999       428       352       353       551
 4767  7.801100e+09  7801099999       926       743       758      1149
 4768  7.802100e+09  7802099999      1488      1010      1197      1846
 4769  7.803100e+09  7803099999      1063       704       849      1319

       Rent50_4  State           cbsasub  \
 0         1424      1  METRO33860M33860
 1         1577      1  METRO19300M19300
 2          929      1  NCNTY01005N01005
 3         1360      1  METRO13820M13820
 4         1360      1  METRO13820M13820
 ...        ...    ...               ...
 4765       980     72  METRO41980MM7440
 4766       747     72  METRO38660M49500
 4767      1269     78  NCNTY78010N78010
 4768      2040     78  NCNTY78020N78020
 4769      1457     78  NCNTY78030N78030

                                       areaname  county  CouSub  \
 0                           Montgomery, AL MSA     1.0   99999
 1                Daphne-Fairhope-Foley, AL MSA     3.0   99999
 2                           Barbour County, AL     5.0   99999

In [29]:
# Adding year column for the year 2005
for df in combined_list:
    if 'year' not in df.columns:
        df['year'] = 2005

In [30]:
# Rechecking
combined_list

[      state_code  county_code  county_sub_code             cntyname town_name  \
 0             48           59            99999      Callahan County       NaN
 1             48          253            99999         Jones County       NaN
 2             48          441            99999        Taylor County       NaN
 3             72            3            99999     Aguada Municipio       NaN
 4             72            5            99999  Aguadilla Municipio       NaN
 ...          ...          ...              ...                  ...       ...
 4759          72          141            99999     Utuado Municipio       NaN
 4760          72          147            99999    Vieques Municipio       NaN
 4761          78           10            99999            St. Croix       NaN
 4762          78           20            99999             St. John       NaN
 4763          78           30            99999           St. Thomas       NaN

                        hud_areaname    fips2025  rent_50_0  rent_50_1  \
 0                   Abilene, TX MSA  4805999999       1075       1085
 1                   Abilene, TX MSA  4825399999       1075       1085
 2                   Abilene, TX MSA  4844199999       1075       1085
 3                 Aguadilla, PR MSA  7200399999        505        508
 4                 Aguadilla, PR MSA  7200599999        505        508
 ...                             ...         ...        ...        ...
 4759  Puerto Rico HUD Nonmetro Area  7214199999        434        454
 4760  Puerto Rico HUD Nonmetro Area  7214799999        434        454
 4761           St. Croix Island, VI  7801099999       1106       1113
 4762            St. John Island, VI  7802099999       1760       1771
 4763          St. Thomas Island, VI  7803099999       1119       1299

       rent_50_2  rent_50_3  rent_50_4     hud_area_code  pop2023 state_alpha  \
 0          1358       1759       2115  METRO10180M10180    13869          TX
 1          1358       1759       2115  METRO10180M10180    19758          TX
 2          1358       1759       2115  METRO10180M10180   143029          TX
 3           594        716        796  METRO10380M10380    37998          PR
 4           594        716        796  METRO10380M10380    54752          PR
 ...         ...        ...        ...               ...      ...         ...
 4759        498        693        752  NCNTY72923N72923    28155          PR
 4760        498        693        752  NCNTY72923N72923     8199          PR
 4761       1330       1609       1761  NCNTY78010N78010    53234          VI
 4762       2218       2659       2937  NCNTY78020N78020     4197          VI
 4763       1603       1922       2122  NCNTY78030N78030    51181          VI

       year
 0     2026
 1     2026
 2     2026
 3     2026
 4     2026
 ...    ...
 4759  2026
 4760  2026
 4761  2026
 4762  2026
 4763  2026

 [4764 rows x 16 columns],
         fips2010  rent50_0  rent50_1  rent50_2  rent50_3  rent50_4  state  \
 0     4805999999       761       789      1028      1383      1764     48
 1     4825399999       761       789      1028      1383      1764     48
 2     4844199999       761       789      1028      1383      1764     48
 3     7200399999       401       414       472       602       720     72
 4     7200599999       401       414       472       602       720     72
 ...          ...       ...       ...       ...       ...       ...    ...
 4761  7213399999       386       395       450       599       666     72
 4762  7214799999       386       395       450       599       666     72
 4763  7801099999       926       945      1154      1435      1565     78
 4764  7802099999      1230      1458      1812      2254      2457     78
 4765  7803099999       866      1044      1307      1626      1772     78

              cbsasub21                                areaname21  county  \
 0     METRO10180M10180                           Abilene, TX MSA      59
 1     METRO10180M10180                           Abilene, TX MSA     253
 2     METRO10180M10180                           Abilene, TX MSA     441
 3     METRO10380M10380  Aguadilla-Isabela, PR HUD Metro FMR Area       3
 4     METRO10380M10380  Aguadilla-Isabela, PR HUD Metro FMR Area       5
 ...                ...                                       ...     ...
 4761  NCNTY72923N72923             Puerto Rico HUD Nonmetro Area     133
 4762  NCNTY72923N72923             Puerto Rico HUD Nonmetro Area     147
 4763  NCNTY78010N78010                      St. Croix Island, VI      10
 4764  NCNTY78020N78020                       St. John Island, VI      20
 4765  NCNTY78030N78030                     St. Thomas Island, VI      30

       cousub                cntyname                    name  pop2017  hu2017  \
 0      99999         Callahan County         Callahan County    13660    6637
 1      99999            Jones County            Jones County    19970    7292
 2      99999           Taylor County           Taylor County   135370   56978
 3      99999        Aguada Municipio        Aguada Municipio    39470   17385
 4      99999     Aguadilla Municipio     Aguadilla Municipio    55720   27301
 ...      ...                     ...                     ...      ...     ...
 4761   99999  Santa Isabel Municipio  Santa Isabel Municipio    22475    9417
 4762   99999       Vieques Municipio       Vieques Municipio     8930    5101
 4763   99999               St. Croix               St. Croix    53234   25275
 4764   99999                St. John                St. John     4197    3453
 4765   99999              St. Thomas              St. Thomas    51181   27173

      state_alpha  year
 0             TX  2021
 1             TX  2021
 2             TX  2021
 3             PR  2021
 4             PR  2021
 ...          ...   ...
 4761          PR  2021
 4762          PR  2021
 4763          VI  2021
 4764          VI  2021
 4765          VI  2021

 [4766 rows x 17 columns],
         fips2010  rent50_0  rent50_1  rent50_2  rent50_3  rent50_4  state  \
 0     4805999999       673       699       920      1209      1560     48
 1     4825399999       673       699       920      1209      1560     48
 2     4844199999       673       699       920      1209      1560     48
 3     7200399999       386       397       452       591       713     72
 4     7200599999       386       397       452       591       713     72
 ...          ...       ...       ...       ...       ...       ...    ...
 4762  7213399999       370       373       437       582       656     72
 4763  7214799999       370       373       437       582       656     72
 4764  7801099999       887       905      1105      1377      1497     78
 4765  7802099999      1177      1394      1733      2160      2348     78
 4766  7803099999       829      1000      1251      1559      1695     78

              cbsasub20                                areaname20  county  \
 0     METRO10180M10180                           Abilene, TX MSA      59
 1     METRO10180M10180                           Abilene, TX MSA     253
 2     METRO10180M10180                           Abilene, TX MSA     441
 3     METRO10380M10380  Aguadilla-Isabela, PR HUD Metro FMR Area       3
 4     METRO10380M10380  Aguadilla-Isabela, PR HUD Metro FMR Area       5
 ...                ...                                       ...     ...
 4762  NCNTY72923N72923             Puerto Rico HUD Nonmetro Area     133
 4763  NCNTY72923N72923             Puerto Rico HUD Nonmetro Area     147
 4764  NCNTY78010N78010                      St. Croix Island, VI      10
 4765  NCNTY78020N78020                       St. John Island, VI      20
 4766  NCNTY78030N78030                     St. Thomas Island, VI      30

       cousub                cntyname                    name  pop2017  hu2017  \
 0      99999         Callahan County         Callahan County    13660    6637
 1      99999            Jones County            Jones County    19970    7292
 2      99999           Taylor County           Taylor County   135370   56978
 3      99999        Aguada Municipio        Aguada Municipio    39470   17385
 4      99999     Aguadilla Municipio     Aguadilla Municipio    55720   27301
 ...      ...                     ...                     ...      ...     ...
 4762   99999  Santa Isabel Municipio  Santa Isabel Municipio    22475    9417
 4763   99999       Vieques Municipio       Vieques Municipio     8930    5101
 4764   99999               St. Croix               St. Croix    53234   25275
 4765   99999                St. John                St. John     4197    3453
 4766   99999              St. Thomas              St. Thomas    51181   27173

      state_alpha  year
 0             TX  2020
 1             TX  2020
 2             TX  2020
 3             PR  2020
 4             PR  2020
 ...          ...   ...
 4762          PR  2020
 4763          PR  2020
 4764          VI  2020
 4765          VI  2020
 4766          VI  2020

 [4767 rows x 17 columns],
         fips2010  rent50_0  rent50_1  rent50_2  rent50_3  rent50_4  state  \
 0     4805999999       642       667       882      1142      1467     48
 1     4825399999       642       667       882      1142      1467     48
 2     4844199999       642       667       882      1142      1467     48
 3     7200399999       388       398       456       606       732     72
 4     7200599999       388       398       456       606       732     72
 ...          ...       ...       ...       ...       ...       ...    ...
 4763  7213399999       358       367       444       595       696     72
 4764  7214799999       358       367       444       595       696     72
 4765  7801099999       779       794       970      1215      1311     78
 4766  7802099999      1034      1225      1523      1908      2059     78
 4767  7803099999       744       897      1123      1407      1518     78

              cbsasub19                                areaname19  county  \
 0     METRO10180M10180                           Abilene, TX MSA      59
 1     METRO10180M10180                           Abilene, TX MSA     253
 2     METRO10180M10180                           Abilene, TX MSA     441
 3     METRO10380M10380  Aguadilla-Isabela, PR HUD Metro FMR Area       3
 4     METRO10380M10380  Aguadilla-Isabela, PR HUD Metro FMR Area       5
 ...                ...                                       ...     ...
 4763  NCNTY72923N72923             Puerto Rico HUD Nonmetro Area     133
 4764  NCNTY72923N72923             Puerto Rico HUD Nonmetro Area     147
 4765  NCNTY78010N78010                      St. Croix Island, VI      10
 4766  NCNTY78020N78020                       St. John Island, VI      20
 4767  NCNTY78030N78030                     St. Thomas Island, VI      30

       cousub                cntyname                    name  pop2010  hu2010  \
 0      99999         Callahan County         Callahan County    13544    6549
 1      99999            Jones County            Jones County    20202    7422
 2      99999           Taylor County           Taylor County   131506   55750
 3      99999        Aguada Municipio        Aguada Municipio    41959   18258
 4      99999     Aguadilla Municipio     Aguadilla Municipio    60949   28430
 ...      ...                     ...                     ...      ...     ...
 4763   99999  Santa Isabel Municipio  Santa Isabel Municipio    23274    9575
 4764   99999       Vieques Municipio       Vieques Municipio     9301    5541
 4765   99999               St. Croix               St. Croix    53234   25275
 4766   99999                St. John                St. John     4197    3453
 4767   99999              St. Thomas              St. Thomas    51181   27173

      state_alpha  year
 0             TX  2019
 1             TX  2019
 2             TX  2019
 3             PR  2019
 4             PR  2019
 ...          ...   ...
 4763          PR  2019
 4764          PR  2019
 4765          VI  2019
 4766          VI  2019
 4767          VI  2019

 [4768 rows x 17 columns],
         fips2010  rent50_0  rent50_1  rent50_2  rent50_3  rent50_4  state  \
 0      100199999       631       742       890      1133      1558      1
 1      100399999       786       809       929      1351      1578      1
 2      100599999       527       531       706       885       998      1
 3      100799999       749       832       955      1273      1424      1
 4      100999999       749       832       955      1273      1424      1
 ...          ...       ...       ...       ...       ...       ...    ...
 4765  7215199999       452       478       577       769       961     72
 4766  7215399999       330       340       390       511       687     72
 4767  7801099999       816       833      1017      1275      1385     78
 4768  7802099999      1084      1284      1596      2001      2174     78
 4769  7803099999       763       921      1152      1444      1569     78

              cbsasub18                                areaname18  county  \
 0     METRO33860M33860                        Montgomery, AL MSA       1
 1     METRO19300M19300             Daphne-Fairhope-Foley, AL MSA       3
 2     NCNTY01005N01005                        Barbour County, AL       5
 3     METRO13820M13820  Birmingham-Hoover, AL HUD Metro FMR Area       7
 4     METRO13820M13820  Birmingham-Hoover, AL HUD Metro FMR Area       9
 ...                ...                                       ...     ...
 4765  METRO41980MM7440  San Juan-Guaynabo, PR HUD Metro FMR Area     151
 4766  METRO38660M49500              Yauco, PR HUD Metro FMR Area     153
 4767  NCNTY78010N78010                      St. Croix Island, VI      10
 4768  NCNTY78020N78020                       St. John Island, VI      20
 4769  NCNTY78030N78030                     St. Thomas Island, VI      30

       cousub           cntyname               name   pop2010    hu2010  \
 0      99999     Autauga County     Autauga County   54571.0   22135.0
 1      99999     Baldwin County     Baldwin County  182265.0  104061.0
 2      99999     Barbour County     Barbour County   27457.0   11829.0
 3      99999        Bibb County        Bibb County   22915.0    8981.0
 4      99999      Blount County      Blount County   57322.0   23887.0
 ...      ...                ...                ...       ...       ...
 4765   99999  Yabucoa Municipio  Yabucoa Municipio   37941.0   15798.0
 4766   99999    Yauco Municipio    Yauco Municipio   42043.0   18020.0
 4767   99999          St. Croix          St. Croix   53234.0   25275.0
 4768   99999           St. John           St. John    4197.0    3453.0
 4769   99999         St. Thomas         St. Thomas   51181.0   27173.0

      state_alpha  year
 0             AL  2018
 1             AL  2018
 2             AL  2018
 3             AL  2018
 4             AL  2018
 ...          ...   ...
 4765          PR  2018
 4766          PR  2018
 4767          VI  2018
 4768          VI  2018
 4769          VI  2018

 [4770 rows x 17 columns],
         fips2010      fips2000  Rent50_2  Rent50_0  Rent50_1  Rent50_3  \
 0      100199999  1.002000e+08       886       633       735      1136
 1      100399999  1.004000e+08      1047       865       908      1524
 2      100599999  1.006000e+08       722       540       543       903
 3      100799999  1.008000e+08       937       719       812      1258
 4      100999999  1.010000e+08       937       719       812      1258
 ...          ...           ...       ...       ...       ...       ...
 4764  7215199999  7.215200e+09       605       471       502       813
 4765  7215399999  7.215400e+09       432       357       374       555
 4766  7801099999  7.801100e+09       952       764       780      1181
 4767  7802099999  7.802100e+09      1529      1038      1230      1897
 4768  7803099999  7.803100e+09      1093       724       873      1356

       Rent50_4  State           cbsasub  \
 0         1536      1  METRO33860M33860
 1         1751      1  METRO19300M19300
 2         1031      1  NCNTY01005N01005
 3         1405      1  METRO13820M13820
 4         1405      1  METRO13820M13820
 ...        ...    ...               ...
 4764      1011     72  METRO41980MM7440
 4765       761     72  METRO38660M49500
 4766      1305     78  NCNTY78010N78010
 4767      2096     78  NCNTY78020N78020
 4768      1498     78  NCNTY78030N78030

                                       areaname  county  CouSub  \
 0                           Montgomery, AL MSA     1.0   99999
 1                Daphne-Fairhope-Foley, AL MSA     3.0   99999
 2                           Barbour County, AL     5.0   99999
 3     Birmingham-Hoover, AL HUD Metro FMR Area     7.0   99999
 4     Birmingham-Hoover, AL HUD Metro FMR Area     9.0   99999
 ...                                        ...     ...     ...
 4764  San Juan-Guaynabo, PR HUD Metro FMR Area   151.0   99999
 4765              Yauco, PR HUD Metro FMR Area   153.0   99999
 4766                      St. Croix Island, VI    10.0   99999
 4767                       St. John Island, VI    20.0   99999
 4768                     St. Thomas Island, VI    30.0   99999

              countyname   county_town_name   pop2010    hu2010 state_alpha  \
 0        Autauga County     Autauga County   54571.0   22135.0          AL
 1        Baldwin County     Baldwin County  182265.0  104061.0          AL
 2        Barbour County     Barbour County   27457.0   11829.0          AL
 3           Bibb County        Bibb County   22915.0    8981.0          AL
 4         Blount County      Blount County   57322.0   23887.0          AL
 ...                 ...                ...       ...       ...         ...
 4764  Yabucoa Municipio  Yabucoa Municipio   37941.0   15798.0          PR
 4765    Yauco Municipio    Yauco Municipio   42043.0   18020.0          PR
 4766          St. Croix          St. Croix   53234.0   25275.0          VI
 4767           St. John           St. John    4197.0    3453.0          VI
 4768         St. Thomas         St. Thomas   51181.0   27173.0          VI

       year
 0     2017
 1     2017
 2     2017
 3     2017
 4     2017
 ...    ...
 4764  2017
 4765  2017
 4766  2017
 4767  2017
 4768  2017

 [4769 rows x 18 columns],
           fips2000    fips2010  Rent50_2  Rent50_0  Rent50_1  Rent50_3  \
 0     1.002000e+08   100199999       840       602       690      1097
 1     1.004000e+08   100399999       935       770       808      1363
 2     1.006000e+08   100599999       678       503       507       841
 3     1.008000e+08   100799999       914       666       790      1234
 4     1.010000e+08   100999999       914       666       790      1234
 ...            ...         ...       ...       ...       ...       ...
 4765  7.215200e+09  7215199999       600       446       499       806
 4766  7.215400e+09  7215399999       428       352       353       551
 4767  7.801100e+09  7801099999       926       743       758      1149
 4768  7.802100e+09  7802099999      1488      1010      1197      1846
 4769  7.803100e+09  7803099999      1063       704       849      1319

       Rent50_4  State           cbsasub  \
 0         1424      1  METRO33860M33860
 1         1577      1  METRO19300M19300
 2          929      1  NCNTY01005N01005
 3         1360      1  METRO13820M13820
 4         1360      1  METRO13820M13820
 ...        ...    ...               ...
 4765       980     72  METRO41980MM7440
 4766       747     72  METRO38660M49500
 4767      1269     78  NCNTY78010N78010
 4768      2040     78  NCNTY78020N78020
 4769      1457     78  NCNTY78030N78030

                                       areaname  county  CouSub  \
 0                           Montgomery, AL MSA     1.0   99999
 1                Daphne-Fairhope-Foley, AL MSA     3.0   99999
 2                           Barbour County, AL     5.0   99999

In [31]:
# Setting up Data Cleaning Function
def clean_func(df):
    df = df.copy()

    # Standardizing the column names
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
    )

    # Renaming inconsistent columns names
    rename_map = {
        "rent50_0": "rent_50_0",
        "rent50_1": "rent_50_1",
        "rent50_2": "rent_50_2",
        "rent50_3": "rent_50_3",
        "rent50_4": "rent_50_4",

        "rent0": "rent_50_0",
        "rent1": "rent_50_1",
        "rent2": "rent_50_2",
        "rent3": "rent_50_3",
        "rent4": "rent_50_4",

        "rent0br": "rent_50_0",
        "rent1br": "rent_50_1",
        "rent2br": "rent_50_2",
        "rent3br": "rent_50_3",
        "rent4br": "rent_50_4",

        "rent_0": "rent_50_0",
        "rent_1": "rent_50_1",
        "rent_2": "rent_50_2",
        "rent_3": "rent_50_3",
        "rent_4": "rent_50_4",

        "rent50_0bed": "rent_50_0",
        "rent50_1bed": "rent_50_1",
        "rent50_2bed": "rent_50_2",
        "rent50_3bed": "rent_50_3",
        "rent50_4bed": "rent_50_4",

        "state": "state_code",
        "state_alpha": "state_alpha",
        "st": "state_alpha",

        "countyname": "cntyname",
        "county_town_name": "cntyname",
        "name": "cntyname",

        "areaname": "hud_areaname",
        "areaname21": "hud_areaname",
        "areaname20": "hud_areaname",
        "areaname19": "hud_areaname",
        "msaname": "hud_areaname",

        "fips": "fips",
        "fips2010": "fips",
        "fips2000": "fips",
        "fips2025": "fips",

        "pop": "pop",
        "pop2000": "pop",
        "pop100": "pop",
    }

    df = df.rename(columns=rename_map)

    # Creating state_alpha and state_code if not present in dataframes
    if 'state_alpha' not in df.columns:
      df['state_alpha'] = pd.NA
    if 'state_code' not in df.columns:
      df['state_code'] = pd.NA
    # Ensuring string format type for state_alpha
    df['state_alpha'] = (
        df['state_alpha']
        .astype("string")
        .str.strip()
        .str.upper()
        )

    # Creating state_code - state_alpha mapping
    state_alpha_to_code = {
    'AL': 1, 'AK': 2, 'AZ': 4, 'AR': 5, 'CA': 6,
    'CO': 8, 'CT': 9, 'DE': 10, 'DC': 11, 'FL': 12,
    'GA': 13, 'HI': 15, 'ID': 16, 'IL': 17, 'IN': 18,
    'IA': 19, 'KS': 20, 'KY': 21, 'LA': 22, 'ME': 23,
    'MD': 24, 'MA': 25, 'MI': 26, 'MN': 27, 'MS': 28,
    'MO': 29, 'MT': 30, 'NE': 31, 'NV': 32, 'NH': 33,
    'NJ': 34, 'NM': 35, 'NY': 36, 'NC': 37, 'ND': 38,
    'OH': 39, 'OK': 40, 'OR': 41, 'PA': 42, 'RI': 44,
    'SC': 45, 'SD': 46, 'TN': 47, 'TX': 48, 'UT': 49,
    'VT': 50, 'VA': 51, 'WA': 53, 'WV': 54, 'WI': 55,
    'WY': 56,
    'PR': 72,
    'VI': 78,
    'GU': 66,
    'MP': 69,
    'AS': 60
    }

    state_code_to_alpha = {v: k for k, v in state_alpha_to_code.items()}


    # Fixing missing state_code and state_alpha
    if 'state_code' not in df.columns or df['state_code'].isna().any():
      df['state_code'] = df['state_code'].fillna(
          df['state_alpha'].map(state_alpha_to_code)
          )

    if 'state_alpha' not in df.columns or df['state_alpha'].isna().any():
      df['state_alpha'] = df['state_alpha'].fillna(
          df['state_code'].map(state_code_to_alpha)
          )

    # Confirming columns exist across dataframes
    final_cols = [
        'state_code', 'county_code', 'county_sub_code',
        'cntyname', 'town_name', 'hud_areaname',
        'fips', 'hud_area_code',
        'rent_50_0', 'rent_50_1', 'rent_50_2',
        'rent_50_3', 'rent_50_4',
        'population', 'state_alpha', 'year'
    ]

    for col in final_cols:
        if col not in df.columns:
            df[col] = np.nan

    df = df.loc[:, ~df.columns.duplicated()]

    # Fixing nuemric Data type
    numeric_cols = ['rent_50_0', 'rent_50_1',
        'rent_50_2', 'rent_50_3', 'rent_50_4'
    ]

    for col in numeric_cols:
        df[col] = pd.to_numeric(df[col], errors='coerce')

    # Fixing categorical data types
    str_cols = ['cntyname', 'state_alpha']

    for col in str_cols:
      df[col] = df[col].astype(str)
      df[col] = df[col].map(str).str.strip()
      df[col] = df[col].replace(['None', 'nan', 'NaN'], pd.NA)

    # Agggregating the data by state
    grouped_yearly = df.groupby(
        ['year','state_code', 'state_alpha']
        )[['rent_50_0', 'rent_50_1','rent_50_2', 'rent_50_3', 'rent_50_4']].mean().reset_index()

    return df

# Data Cleaning
cleaned_dataframes = [clean_func(df) for df in combined_list]

/tmp/ipykernel_2578/802795931.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['state_code'] = df['state_code'].fillna(

In [32]:
# Combining cleaned dataframes through Concatenate
combined_rent_inflation = pd.concat(cleaned_dataframes, ignore_index=True)

# Getting Overview of combined data
print(combined_rent_inflation.shape)
# Ensuring all years are captured
combined_rent_inflation.year.value_counts()

(115209, 40)

year
2016    4770
2018    4770
2015    4769
2017    4769
2019    4768
2020    4767
2014    4766
2021    4766
2013    4766
2012    4765
2022    4765
2011    4765
2026    4764
2023    4764
2024    4764
2025    4764
2010    4763
2009    4763
2007    4763
2006    4763
2008    4763
2004    3265
2003    3263
2005    3244
2001    2680
2002    2680
Name: count, dtype: int64

In [33]:
# Saving combined dataset
combined_rent_inflation.to_csv("combined_rent_inflation.csv")

In [36]:
combined_rent_inflation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115209 entries, 0 to 115208
Data columns (total 40 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   state_code       115207 non-null  object
 1   county_code      23821 non-null   object
 2   county_sub_code  23821 non-null   object
 3   cntyname         109848 non-null  object
 4   town_name        8026 non-null    object
 5   hud_areaname     101022 non-null  object
 6   fips             95306 non-null   object
 7   rent_50_0        115208 non-null  float64
 8   rent_50_1        115208 non-null  float64
 9   rent_50_2        115208 non-null  float64
 10  rent_50_3        115208 non-null  float64
 11  rent_50_4        115208 non-null  float64
 12  hud_area_code    19056 non-null   object
 13  pop2023          4764 non-null    float64
 14  state_alpha      115209 non-null  object
 15  year             115209 non-null  int64
 16  population       0 non-null       float64
 17  cbsasub21        4766 non-null    object
 18  county           86022 non-null   float64
 19  cousub           76256 non-null   float64
 20  pop2017          14298 non-null   object
 21  hu2017           9533 non-null    float64
 22  cbsasub20        4767 non-null    object
 23  cbsasub19        4768 non-null    object
 24  pop2010          33366 non-null   float64
 25  hu2010           33366 non-null   float64
 26  cbsasub18        4770 non-null    object
 27  areaname18       4770 non-null    object
 28  cbsasub          57185 non-null   object
 29  pop              43116 non-null   float64
 30  fmr_area         3244 non-null    float64
 31  msa              9771 non-null    float64
 32  stco             3243 non-null    float64
 33  fmrtype          6528 non-null    float64
 34  statename        6528 non-null    object
 35  fmrarea          3263 non-null    float64
 36  id_agis2         5360 non-null    object
 37  pop2020          14292 non-null   object
 38  areaname22       4765 non-null    object
 39  cbsasub22        4765 non-null    object
dtypes: float64(18), int64(1), object(21)
memory usage: 35.2+ MB

In [37]:
# Filtering for the state of New York
ny_combined_rent_inflation = combined_rent_inflation[combined_rent_inflation["state_alpha"] == "NY"].copy()
print(ny_combined_rent_inflation.shape)
ny_combined_rent_inflation.head()

(1505, 40)

,state_code,county_code,county_sub_code,cntyname,town_name,hud_areaname,fips,rent_50_0,rent_50_1,rent_50_2,...,fmr_area,msa,stco,fmrtype,statename,fmrarea,id_agis2,pop2020,areaname22,cbsasub22
17,36,1,99999,Albany County,NaN,"Albany-Schenectady-Troy, NY MSA",3600199999,1328.0,1545.0,1856.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,36,83,99999,Rensselaer County,NaN,"Albany-Schenectady-Troy, NY MSA",3608399999,1328.0,1545.0,1856.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,36,91,99999,Saratoga County,NaN,"Albany-Schenectady-Troy, NY MSA",3609199999,1328.0,1545.0,1856.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,36,93,99999,Schenectady County,NaN,"Albany-Schenectady-Troy, NY MSA",3609399999,1328.0,1545.0,1856.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,36,95,99999,Schoharie County,NaN,"Albany-Schenectady-Troy, NY MSA",3609599999,1328.0,1545.0,1856.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
# Saving combined dataset
ny_combined_rent_inflation.to_csv("ny_combined_rent_inflation.csv")

## Investment Data - FRED

In [ ]:
import pandas as pd

# Getting GDPI (Gross Domestic Private Investment) Annual for USA
url = "https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23ebf3fb&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=1320&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=GPDI&scale=left&cosd=1947-01-01&coed=2025-10-01&line_color=%230073e6&link_values=false&line_style=solid&mark_type=none&mw=3&lw=3&ost=-99999&oet=99999&mma=0&fml=a&fq=Quarterly&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=2026-03-24&revision_date=2026-03-24&nd=1947-01-01"

# Importing CSV
df_investment_USA = pd.read_csv(url)
df_investment_USA

    observation_date      GPDI
0         1947-01-01    35.854
1         1947-04-01    34.505
2         1947-07-01    34.911
3         1947-10-01    43.250
4         1948-01-01    47.202
..               ...       ...
311       2024-10-01  5261.830
312       2025-01-01  5556.216
313       2025-04-01  5358.632
314       2025-07-01  5419.029
315       2025-10-01  5516.971

[316 rows x 2 columns]

In [ ]:
# Saving Data
df_investment_USA.to_csv("df_investment_USA.csv")

## Investment Data - BEA

In [ ]:
# API Request Attempt

import requests
import pandas as pd
from tqdm import tqdm

BEA_API_KEY = "D079635D-A08D-4E4E-903B-4231899408AD"
years = list(range(2005, 2025))
all_data = []

for year in tqdm(years):
    params = {
        "UserID": BEA_API_KEY,
        "Method": "GetData",
        "DataSetName": "GDPbyIndustry",
        "TableID": "SQGDP2",
        "GeoFips": "STATE",
        "Industry": "53",
        "Year": str(year),
        "Frequency": "A",
        "ResultFormat": "json"
    }
    response = requests.get("https://apps.bea.gov/api/data", params=params)
    data = response.json()

100%|██████████| 20/20 [00:02<00:00,  7.75it/s]

In [ ]:
data

{'BEAAPI': {'Request': {'RequestParam': [{'ParameterName': 'USERID',
     'ParameterValue': 'D079635D-A08D-4E4E-903B-4231899408AD'},
    {'ParameterName': 'METHOD', 'ParameterValue': 'GETDATA'},
    {'ParameterName': 'DATASETNAME', 'ParameterValue': 'GDPBYINDUSTRY'},
    {'ParameterName': 'TABLEID', 'ParameterValue': 'SQGDP2'},
    {'ParameterName': 'GEOFIPS', 'ParameterValue': 'STATE'},
    {'ParameterName': 'INDUSTRY', 'ParameterValue': '53'},
    {'ParameterName': 'YEAR', 'ParameterValue': '2024'},
    {'ParameterName': 'FREQUENCY', 'ParameterValue': 'A'},
    {'ParameterName': 'RESULTFORMAT', 'ParameterValue': 'JSON'}]},
  'Results': {'Error': {'APIErrorCode': '98',
    'APIErrorDescription': 'Internal API error retrieving data.'}}}}

API Fails to download the exact data for GDP Private Industry. Importing Data Downloaded from BEA:

[GDP_Private_Industry](https://apps.bea.gov/itable/?ReqID=70&step=1#eyJhcHBpZCI6NzAsInN0ZXBzIjpbMSwyOSwyNSwzMSwyNiwyNywzMF0sImRhdGEiOltbIlRhYmxlSWQiLCI1MDEiXSxbIk1ham9yX0FyZWEiLCI0Il0sWyJTdGF0ZSIsWyJYWCJdXSxbIkFyZWEiLFsiWFgiXV0sWyJTdGF0aXN0aWMiLFsiMiJdXSxbIlVuaXRfb2ZfbWVhc3VyZSIsIkxldmVscyJdLFsiWWVhciIsWyItMSJdXSxbIlllYXJCZWdpbiIsIi0xIl0sWyJZZWFyX0VuZCIsIi0xIl1dfQ==)

### Data Collection

In [8]:
import pandas as pd
import glob
import os

# Import Function
def import_gdp_files(path_pattern="Table_GDP_PI_*.csv"):

    dataframes = {}

    files = sorted(glob.glob(path_pattern))

    for file in files:

        year = os.path.basename(file).split("_")[-1].split(".")[0]

        df = pd.read_csv(
            file,
            skiprows=3
        )

        dataframes[int(year)] = df

        print(f"Loaded {file} -> {df.shape}")

    return dataframes

In [6]:
# Applying Functions for data importation
gdp_data = import_gdp_files()

Loaded Table_GDP_PI_2001.csv -> (3139, 3)
Loaded Table_GDP_PI_2002.csv -> (3139, 3)
Loaded Table_GDP_PI_2003.csv -> (3139, 3)
Loaded Table_GDP_PI_2004.csv -> (3139, 3)
Loaded Table_GDP_PI_2005.csv -> (3139, 3)
Loaded Table_GDP_PI_2006.csv -> (3139, 3)
Loaded Table_GDP_PI_2007.csv -> (3139, 3)
Loaded Table_GDP_PI_2008.csv -> (3139, 3)
Loaded Table_GDP_PI_2009.csv -> (3139, 3)
Loaded Table_GDP_PI_2010.csv -> (3139, 3)
Loaded Table_GDP_PI_2011.csv -> (3139, 3)
Loaded Table_GDP_PI_2012.csv -> (3139, 3)
Loaded Table_GDP_PI_2013.csv -> (3139, 3)
Loaded Table_GDP_PI_2014.csv -> (3139, 3)
Loaded Table_GDP_PI_2015.csv -> (3139, 3)
Loaded Table_GDP_PI_2016.csv -> (3139, 3)
Loaded Table_GDP_PI_2017.csv -> (3139, 3)
Loaded Table_GDP_PI_2018.csv -> (3139, 3)
Loaded Table_GDP_PI_2019.csv -> (3139, 3)
Loaded Table_GDP_PI_2020.csv -> (3139, 3)
Loaded Table_GDP_PI_2021.csv -> (3139, 3)
Loaded Table_GDP_PI_2022.csv -> (3139, 3)
Loaded Table_GDP_PI_2023.csv -> (3139, 3)
Loaded Table_GDP_PI_2024.csv -> (3139, 3)

### Data Cleaning

In [10]:
# Cleaning + Wide/Long Function
def clean_merge_gdp(dataframes):

    cleaned = []

    for year, df in dataframes.items():

        df = df[["GeoFIPS", "GeoName", str(year)]].copy()

        # keeping only valid numeric GeoFIPS rows
        df["GeoFIPS"] = pd.to_numeric(
            df["GeoFIPS"],
            errors="coerce"
        )

        df = df[df["GeoFIPS"].notna()].copy()

        # converting GeoFIPS
        df["GeoFIPS"] = df["GeoFIPS"].astype(int)

        # splitting county and state
        split_cols = df["GeoName"].str.split(",", expand=True)

        df["county_name"] = split_cols[0].str.strip()

        df["state_alpha"] = split_cols[1].str.strip()

        # renaming GDP column
        df.rename(columns={str(year): f"GDP_PI_{year}"}, inplace=True)

        cleaned.append(df)

    # initializing wide dataframe
    wide_df = cleaned[0][
        [
            "GeoFIPS",
            "GeoName",
            "county_name",
            "state_alpha",
            cleaned[0].columns[2]
        ]
    ].copy()

    # merging remaining years
    for df in cleaned[1:]:

        gdp_col = [c for c in df.columns if "GDP_PI_" in c][0]

        wide_df = wide_df.merge(
            df[["GeoFIPS", gdp_col]],
            on="GeoFIPS",
            how="outer"
        )

    # long format
    long_df = wide_df.melt(
        id_vars=[
            "GeoFIPS",
            "GeoName",
            "county_name",
            "state_alpha"
        ],
        var_name="year",
        value_name="GDP_PI"
    )

    # extracting year
    long_df["year"] = (
        long_df["year"]
        .str.replace("GDP_PI_", "", regex=False)
        .astype(int)
    )

    # numeric GDP
    long_df["GDP_PI"] = pd.to_numeric(
        long_df["GDP_PI"],
        errors="coerce"
    )

    return wide_df, long_df

In [16]:
# Data Cleaning and Merging
gdp_wide, gdp_long = clean_merge_gdp(gdp_data)
print(gdp_wide.head())
print(gdp_wide.shape)

   GeoFIPS      GeoName county_name state_alpha GDP_PI_2001 GDP_PI_2002  \
0     1001  Autauga, AL     Autauga          AL      664472      689654
1     1003  Baldwin, AL     Baldwin          AL     2747962     2969499
2     1005  Barbour, AL     Barbour          AL      553608      548419
3     1007     Bibb, AL        Bibb          AL      161083      166252
4     1009   Blount, AL      Blount          AL      535973      548207

  GDP_PI_2003 GDP_PI_2004 GDP_PI_2005 GDP_PI_2006  ... GDP_PI_2015  \
0      713046      845920      870996      962683  ...     1469139
1     3205661     3631195     4210190     4520727  ...     5781395
2      570777      643970      648062      640671  ...      649115
3      180370      199765      207732      213002  ...      288892
4      580813      617286      635634      624020  ...      840717

  GDP_PI_2016 GDP_PI_2017 GDP_PI_2018 GDP_PI_2019 GDP_PI_2020 GDP_PI_2021  \
0     1556140     1520824     1582791     1574667     1612691     1725544
1     6244667     6614034     7123618     7706721     7848051     8872736
2      643224      644416      668470      668800      656103      739539
3      301786      315532      317302      370385      399191      427752
4      776507      835258      907303      894275      803815      985644

  GDP_PI_2022 GDP_PI_2023 GDP_PI_2024
0     2025244     2197843     2016179
1    10162895    11588951    12225374
2      801363      807617      839585
3      467217      505693      519242
4     1087372     1190537     1329509

[5 rows x 28 columns]
(3127, 28)

In [17]:
print(gdp_long.head())
print(gdp_long.shape)

   GeoFIPS      GeoName county_name state_alpha  year     GDP_PI
0     1001  Autauga, AL     Autauga          AL  2001   664472.0
1     1003  Baldwin, AL     Baldwin          AL  2001  2747962.0
2     1005  Barbour, AL     Barbour          AL  2001   553608.0
3     1007     Bibb, AL        Bibb          AL  2001   161083.0
4     1009   Blount, AL      Blount          AL  2001   535973.0
(75048, 6)

In [13]:
# Filtering for New York
ny_gdp_long = gdp_long[
    gdp_long["state_alpha"] == "NY"
].copy()

print(ny_gdp_long.head())
print(ny_gdp_long.shape)

      GeoFIPS          GeoName  county_name state_alpha  year      GDP_PI
1841    36001       Albany, NY       Albany          NY  2001  13068721.0
1842    36003     Allegany, NY     Allegany          NY  2001    689784.0
1843    36005        Bronx, NY        Bronx          NY  2001  17568178.0
1844    36007       Broome, NY       Broome          NY  2001   5435556.0
1845    36009  Cattaraugus, NY  Cattaraugus          NY  2001   1574186.0
(1488, 6)

In [14]:
# Checking for missing entries
ny_gdp_long.isnull().sum()

GeoFIPS        0
GeoName        0
county_name    0
state_alpha    0
year           0
GDP_PI         0
dtype: int64

In [18]:
# Saving Cleaned investment data
gdp_long.to_csv("gdp_long.csv")
gdp_wide.to_csv("gdp_wide.csv")
ny_gdp_long.to_csv("ny_gdp_long.csv")

## Household Income Data - Census.gov API

### Data Collection

In [24]:
import requests
import pandas as pd
from tqdm import tqdm

API_KEY = "D079635D-A08D-4E4E-903B-4231899408AD"

years = list(range(2005, 2023))
all_data = []

for year in tqdm(years):

    url = (
        "https://apps.bea.gov/api/data/"
        f"?UserID={API_KEY}"
        "&method=GetData"
        "&datasetname=Regional"
        "&TableName=CAINC30"
        "&LineCode=10"
        f"&Year={year}"
        "&GeoFIPS=COUNTY"
        "&ResultFormat=json"
    )

    try:

        response = requests.get(url)
        response.raise_for_status()

        json_data = response.json()

        records = json_data["BEAAPI"]["Results"]["Data"]

        df_year = pd.DataFrame(records)

        # selecting columns
        df_year = df_year[
            [
                "GeoFips",
                "GeoName",
                "TimePeriod",
                "DataValue"
            ]
        ].copy()

        # renaming
        df_year.columns = [
            "GeoFIPS",
            "GeoName",
            "year",
            "personal_income"
        ]

        # removing commas
        df_year["personal_income"] = (
            df_year["personal_income"]
            .astype(str)
            .str.replace(",", "", regex=False)
        )

        # numeric conversion
        df_year["personal_income"] = pd.to_numeric(
            df_year["personal_income"],
            errors="coerce"
        )

        # splitting county/state
        split_cols = df_year["GeoName"].str.split(",", expand=True)

        df_year["county_name"] = split_cols[0].str.strip()

        df_year["state_alpha"] = split_cols[1].str.strip()

        all_data.append(df_year)

        print(f"Loaded {year} -> {df_year.shape}")

    except Exception as e:

        print(f"Error for year {year}: {e}")

# combining all years
df_income = pd.concat(all_data, ignore_index=True)

print(df_income.head())

print(df_income.tail())

  6%|▌         | 1/18 [00:02<00:37,  2.22s/it]

Loaded 2005 -> (3149, 6)

 11%|█         | 2/18 [00:03<00:26,  1.64s/it]

Loaded 2006 -> (3149, 6)

 17%|█▋        | 3/18 [00:05<00:28,  1.89s/it]

Loaded 2007 -> (3149, 6)

 22%|██▏       | 4/18 [00:07<00:28,  2.03s/it]

Loaded 2008 -> (3149, 6)

 28%|██▊       | 5/18 [00:10<00:27,  2.10s/it]

Loaded 2009 -> (3149, 6)

 33%|███▎      | 6/18 [00:12<00:25,  2.15s/it]

Loaded 2010 -> (3149, 6)

 39%|███▉      | 7/18 [00:14<00:23,  2.17s/it]

Loaded 2011 -> (3149, 6)

 44%|████▍     | 8/18 [00:15<00:16,  1.67s/it]

Loaded 2012 -> (3149, 6)

 50%|█████     | 9/18 [00:17<00:16,  1.84s/it]

Loaded 2013 -> (3149, 6)

 56%|█████▌    | 10/18 [00:19<00:15,  1.96s/it]

Loaded 2014 -> (3149, 6)

 61%|██████    | 11/18 [00:21<00:14,  2.05s/it]

Loaded 2015 -> (3149, 6)

 67%|██████▋   | 12/18 [00:24<00:12,  2.09s/it]

Loaded 2016 -> (3149, 6)

 72%|███████▏  | 13/18 [00:26<00:10,  2.13s/it]

Loaded 2017 -> (3149, 6)

 78%|███████▊  | 14/18 [00:28<00:08,  2.15s/it]

Loaded 2018 -> (3149, 6)

 83%|████████▎ | 15/18 [00:30<00:06,  2.17s/it]

Loaded 2019 -> (3149, 6)

 89%|████████▉ | 16/18 [00:32<00:04,  2.18s/it]

Loaded 2020 -> (3149, 6)

 94%|█████████▍| 17/18 [00:35<00:02,  2.18s/it]

Loaded 2021 -> (3149, 6)

100%|██████████| 18/18 [00:37<00:00,  2.07s/it]

Loaded 2022 -> (3149, 6)
  GeoFIPS      GeoName  year  personal_income county_name state_alpha
0   01001  Autauga, AL  2005          1440795     Autauga          AL
1   01003  Baldwin, AL  2005          5272521     Baldwin          AL
2   01005  Barbour, AL  2005           665248     Barbour          AL
3   01007     Bibb, AL  2005           468895        Bibb          AL
4   01009   Blount, AL  2005          1340387      Blount          AL
      GeoFIPS         GeoName  year  personal_income county_name state_alpha
56677   56037  Sweetwater, WY  2022          2487038  Sweetwater          WY
56678   56039       Teton, WY  2022         10270477       Teton          WY
56679   56041       Uinta, WY  2022           963574       Uinta          WY
56680   56043    Washakie, WY  2022           426776    Washakie          WY
56681   56045      Weston, WY  2022           354545      Weston          WY

### Data Cleaning

In [25]:
# Checking data structure
df_income.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56682 entries, 0 to 56681
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   GeoFIPS          56682 non-null  object
 1   GeoName          56682 non-null  object
 2   year             56682 non-null  object
 3   personal_income  56682 non-null  int64
 4   county_name      56682 non-null  object
 5   state_alpha      56682 non-null  object
dtypes: int64(1), object(5)
memory usage: 2.6+ MB

In [26]:
# Checking for misisng entries
df_income.isnull().sum()

GeoFIPS            0
GeoName            0
year               0
personal_income    0
county_name        0
state_alpha        0
dtype: int64

In [27]:
# Filtering for New York State
ny_df_income = df_income[
    df_income["state_alpha"] == "NY"
].copy()

print(ny_df_income.head())
print(ny_df_income.shape)

     GeoFIPS          GeoName  year  personal_income  county_name state_alpha
1862   36001       Albany, NY  2005         11476555       Albany          NY
1863   36003     Allegany, NY  2005          1148267     Allegany          NY
1864   36005        Bronx, NY  2005         32553078        Bronx          NY
1865   36007       Broome, NY  2005          5678460       Broome          NY
1866   36009  Cattaraugus, NY  2005          2193492  Cattaraugus          NY
(1116, 6)

In [28]:
# Saving Data
df_income.to_csv("df_income.csv")
ny_df_income.to_csv("ny_df_income.csv")

## Housing Availability Data - Census.gov

### Data Collection

In [29]:
import requests
import pandas as pd
from tqdm import tqdm

API_KEY = "734ceb727a238a7d00971e1354143053179df75b"

years = range(2009, 2024)

all_data = []

for year in tqdm(years):

    url = (
        f"https://api.census.gov/data/{year}/acs/acs5"
        "?get=NAME,B25001_001E"
        "&for=county:*"
        "&in=state:*"
        f"&key={API_KEY}"
    )

    response = requests.get(url)

    data = response.json()

    df = pd.DataFrame(data[1:], columns=data[0])

    df["housing_units"] = pd.to_numeric(
        df["B25001_001E"],
        errors="coerce"
    )

    df["year"] = year

    split_cols = df["NAME"].str.split(",", expand=True)

    df["county_name"] = split_cols[0].str.strip()

    df["state_name"] = split_cols[1].str.strip()

    df["GeoFIPS"] = (
        df["state"] + df["county"]
    )

    all_data.append(
        df[
            [
                "GeoFIPS",
                "county_name",
                "state_name",
                "year",
                "housing_units"
            ]
        ]
    )

df_housing = pd.concat(all_data, ignore_index=True)

print(df_housing.head())

100%|██████████| 15/15 [00:34<00:00,  2.31s/it]

  GeoFIPS       county_name state_name  year  housing_units
0   13091      Dodge County    Georgia  2009           8516
1   13093      Dooly County    Georgia  2009           4620
2   13095  Dougherty County    Georgia  2009          41624
3   13097    Douglas County    Georgia  2009          47770
4   13099      Early County    Georgia  2009           5533

### Data Cleaning

In [30]:
# Checking Data Structure
df_housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48311 entries, 0 to 48310
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   GeoFIPS        48311 non-null  object
 1   county_name    48311 non-null  object
 2   state_name     48311 non-null  object
 3   year           48311 non-null  int64
 4   housing_units  48311 non-null  int64
dtypes: int64(2), object(3)
memory usage: 1.8+ MB

In [31]:
# Checking Missing values
df_housing.isnull().sum()

GeoFIPS          0
county_name      0
state_name       0
year             0
housing_units    0
dtype: int64

In [33]:
# Filtering for New York State
ny_df_housing = df_housing[
    df_housing["state_name"] == "New York"
].copy()

print(ny_df_housing.head())
print(ny_df_housing.shape)

    GeoFIPS         county_name state_name  year  housing_units
979   36001       Albany County   New York  2009         133501
980   36003     Allegany County   New York  2009          25047
981   36005        Bronx County   New York  2009         508895
982   36007       Broome County   New York  2009          89117
983   36009  Cattaraugus County   New York  2009          40612
(930, 5)

In [34]:
# Saving data
df_housing.to_csv("df_housing.csv")
ny_df_housing.to_csv("ny_df_housing.csv")

# Merging Datasets

In [1]:
# Importing Datasets
import pandas as pd

ny_combined_rent_inflation = pd.read_csv("ny_combined_rent_inflation.csv")
ny_df_housing = pd.read_csv("ny_df_housing.csv")
ny_df_income = pd.read_csv("ny_df_income.csv")
ny_gdp_long = pd.read_csv("ny_gdp_long.csv")

In [2]:
# Checking variable names across all datasets
print(ny_combined_rent_inflation.info())
print(ny_df_housing.info())
print(ny_df_income.info())
print(ny_gdp_long.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1505 entries, 0 to 1504
Data columns (total 41 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       1505 non-null   int64
 1   state_code       1505 non-null   float64
 2   county_code      248 non-null    float64
 3   county_sub_code  248 non-null    float64
 4   cntyname         1429 non-null   object
 5   town_name        0 non-null      float64
 6   hud_areaname     1394 non-null   object
 7   fips             1243 non-null   float64
 8   rent_50_0        1505 non-null   float64
 9   rent_50_1        1505 non-null   float64
 10  rent_50_2        1505 non-null   float64
 11  rent_50_3        1505 non-null   float64
 12  rent_50_4        1505 non-null   float64
 13  hud_area_code    248 non-null    object
 14  pop2023          62 non-null     float64
 15  state_alpha      1505 non-null   object
 16  year             1505 non-null   int64
 17  population       0 non-null      float64
 18  cbsasub21        62 non-null     object
 19  county           1181 non-null   float64
 20  cousub           995 non-null    float64
 21  pop2017          125 non-null    float64
 22  hu2017           125 non-null    float64
 23  cbsasub20        63 non-null     object
 24  cbsasub19        63 non-null     object
 25  pop2010          436 non-null    float64
 26  hu2010           436 non-null    float64
 27  cbsasub18        63 non-null     object
 28  areaname18       63 non-null     object
 29  cbsasub          744 non-null    object
 30  pop              620 non-null    float64
 31  fmr_area         62 non-null     float64
 32  msa              186 non-null    float64
 33  stco             62 non-null     float64
 34  fmrtype          124 non-null    float64
 35  statename        124 non-null    object
 36  fmrarea          62 non-null     float64
 37  id_agis2         76 non-null     object
 38  pop2020          186 non-null    float64
 39  areaname22       0 non-null      float64
 40  cbsasub22        0 non-null      float64
dtypes: float64(27), int64(2), object(12)
memory usage: 482.2+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     930 non-null    int64
 1   GeoFIPS        930 non-null    int64
 2   county_name    930 non-null    object
 3   state_name     930 non-null    object
 4   year           930 non-null    int64
 5   housing_units  930 non-null    int64
dtypes: int64(4), object(2)
memory usage: 43.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1116 entries, 0 to 1115
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       1116 non-null   int64
 1   GeoFIPS          1116 non-null   int64
 2   GeoName          1116 non-null   object
 3   year             1116 non-null   int64
 4   personal_income  1116 non-null   int64
 5   county_name      1116 non-null   object
 6   state_alpha      1116 non-null   object
dtypes: int64(4), object(3)
memory usage: 61.2+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1488 entries, 0 to 1487
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   1488 non-null   int64
 1   GeoFIPS      1488 non-null   int64
 2   GeoName      1488 non-null   object
 3   county_name  1488 non-null   object
 4   state_alpha  1488 non-null   object
 5   year         1488 non-null   int64
 6   GDP_PI       1488 non-null   float64
dtypes: float64(1), int64(3), object(3)
memory usage: 81.5+ KB
None

### Data Preparation for Merging

In [3]:
# STANDARDIZIN INFLATION DATASET

# Standardize county variable
ny_combined_rent_inflation["county_name"] = (
    ny_combined_rent_inflation["cntyname"]
    .astype(str)
    .str.strip()
    .str.upper()
)
# Standardize year
ny_combined_rent_inflation["year"] = ny_combined_rent_inflation["year"].astype(int)
# Standardize FIPS (if available)
ny_combined_rent_inflation["GeoFIPS"] = (
    ny_combined_rent_inflation["fips"]
    .fillna(0)
    .astype(int)
)
# Keep only useful columns
ny_combined_rent_inflation = ny_combined_rent_inflation.rename(columns={
    "state_alpha": "state_alpha"
})


# STANDARDIZIN HOUSING DATASET

ny_df_housing["county_name"] = (
    ny_df_housing["county_name"]
    .astype(str)
    .str.strip()
    .str.upper()
)

ny_df_housing["year"] = ny_df_housing["year"].astype(int)
ny_df_housing["GeoFIPS"] = ny_df_housing["GeoFIPS"].astype(int)


# STANDARDIZING INCOME DATASET

ny_df_income["county_name"] = (
    ny_df_income["county_name"]
    .astype(str)
    .str.strip()
    .str.upper()
)

ny_df_income["year"] = ny_df_income["year"].astype(int)
ny_df_income["GeoFIPS"] = ny_df_income["GeoFIPS"].astype(int)
ny_df_income["state_alpha"] = (
   ny_df_income["state_alpha"]
    .astype(str)
    .str.strip()
    .str.upper()
)

# STANDARDIZING GDP DATASET

ny_gdp_long["county_name"] = (
    ny_gdp_long["county_name"]
    .astype(str)
    .str.strip()
    .str.upper()
)

ny_gdp_long["year"] = ny_gdp_long["year"].astype(int)
ny_gdp_long["GeoFIPS"] = ny_gdp_long["GeoFIPS"].astype(int)
ny_gdp_long["state_alpha"] = (
    ny_gdp_long["state_alpha"]
    .astype(str)
    .str.strip()
    .str.upper()
)

# REMOVING WORD "COUNTY" FOR CONSISTENCY


datasets = [ny_combined_rent_inflation, ny_df_housing, ny_df_income, ny_gdp_long]

for df in datasets:
    df["county_name"] = (
        df["county_name"]
        .str.replace(" COUNTY", "", regex=False)
        .str.replace(".", "", regex=False)
        .str.strip()
    )


# CHECKING STANDARDIZATION

print(ny_combined_rent_inflation[["county_name", "year", "GeoFIPS"]].head())
print(ny_df_housing[["county_name", "year", "GeoFIPS"]].head())
print(ny_df_income[["county_name", "year", "GeoFIPS"]].head())
print(ny_gdp_long[["county_name", "year", "GeoFIPS"]].head())

   county_name  year     GeoFIPS
0       ALBANY  2026  3600199999
1   RENSSELAER  2026  3608399999
2     SARATOGA  2026  3609199999
3  SCHENECTADY  2026  3609399999
4    SCHOHARIE  2026  3609599999
   county_name  year  GeoFIPS
0       ALBANY  2009    36001
1     ALLEGANY  2009    36003
2        BRONX  2009    36005
3       BROOME  2009    36007
4  CATTARAUGUS  2009    36009
   county_name  year  GeoFIPS
0       ALBANY  2005    36001
1     ALLEGANY  2005    36003
2        BRONX  2005    36005
3       BROOME  2005    36007
4  CATTARAUGUS  2005    36009
   county_name  year  GeoFIPS
0       ALBANY  2001    36001
1     ALLEGANY  2001    36003
2        BRONX  2001    36005
3       BROOME  2001    36007
4  CATTARAUGUS  2001    36009

### Variable Selection to keep only Relevant Variables

In [4]:
ny_combined_rent_inflation = ny_combined_rent_inflation[["GeoFIPS","county_name", "year",'rent_50_0','rent_50_1','rent_50_2','rent_50_3','rent_50_4']]
ny_df_housing = ny_df_housing[["GeoFIPS","county_name", "year",'housing_units']]
ny_df_income = ny_df_income[["GeoFIPS","county_name", "year",'personal_income']]
ny_gdp_long = ny_gdp_long[["GeoFIPS","county_name", "year",'GDP_PI']]

## Merging ```combined_rent_inflation``` and ```Investment_Private_Industry_extrapolated```

In [5]:
# Merge on state_code and Year
merged_df_1 = pd.merge(
    ny_gdp_long,
    ny_combined_rent_inflation,
    on=["county_name", "year"],
    how='outer'
)

# Reordering columns
merged_df_1 = merged_df_1[["county_name", "year",'GDP_PI',
                       'rent_50_0','rent_50_1','rent_50_2','rent_50_3','rent_50_4']]
merged_df_1

,county_name,year,GDP_PI,rent_50_0,rent_50_1,rent_50_2,rent_50_3,rent_50_4
0,ALBANY,2001,13068721.0,NaN,NaN,NaN,NaN,NaN
1,ALBANY,2002,13424897.0,NaN,NaN,NaN,NaN,NaN
2,ALBANY,2003,14257327.0,444.0,547.0,672.0,844.0,943.0
3,ALBANY,2004,14897956.0,444.0,548.0,673.0,844.0,943.0
4,ALBANY,2005,15541573.0,569.0,600.0,719.0,862.0,927.0
...,...,...,...,...,...,...,...,...
1686,YATES,2022,1170228.0,NaN,NaN,NaN,NaN,NaN
1687,YATES,2023,1212637.0,709.0,806.0,1061.0,1419.0,1425.0
1688,YATES,2024,1224869.0,767.0,862.0,1132.0,1440.0,1622.0
1689,YATES,2025,NaN,811.0,901.0,1182.0,1455.0,1879.0
1690,YATES,2026,NaN,790.0,873.0,1146.0,1388.0,1922.0

## Merging ```merged_df_1``` with ```df_housing_extrapolated```

In [6]:
# Merging datasets
merged_df_2 = pd.merge(
    merged_df_1,
    ny_df_housing[["county_name", "year",'housing_units']],
    on=["county_name", "year"],
    how='left'
)

# Reordering columns
merged_df_2 = merged_df_2[["county_name", "year", 'GDP_PI',
                     'rent_50_0','rent_50_1','rent_50_2','rent_50_3','rent_50_4',
                     'housing_units']]

merged_df_2

,county_name,year,GDP_PI,rent_50_0,rent_50_1,rent_50_2,rent_50_3,rent_50_4,housing_units
0,ALBANY,2001,13068721.0,NaN,NaN,NaN,NaN,NaN,NaN
1,ALBANY,2002,13424897.0,NaN,NaN,NaN,NaN,NaN,NaN
2,ALBANY,2003,14257327.0,444.0,547.0,672.0,844.0,943.0,NaN
3,ALBANY,2004,14897956.0,444.0,548.0,673.0,844.0,943.0,NaN
4,ALBANY,2005,15541573.0,569.0,600.0,719.0,862.0,927.0,NaN
...,...,...,...,...,...,...,...,...,...
1686,YATES,2022,1170228.0,NaN,NaN,NaN,NaN,NaN,13113.0
1687,YATES,2023,1212637.0,709.0,806.0,1061.0,1419.0,1425.0,13143.0
1688,YATES,2024,1224869.0,767.0,862.0,1132.0,1440.0,1622.0,NaN
1689,YATES,2025,NaN,811.0,901.0,1182.0,1455.0,1879.0,NaN
1690,YATES,2026,NaN,790.0,873.0,1146.0,1388.0,1922.0,NaN

## Merging ```merged_df_2``` with ```ny_df_income ```

In [7]:
# Merging Datasets
merged_df_final = pd.merge(
    merged_df_2,
    ny_df_income [["county_name", "year",'personal_income']],
    left_on=["county_name", "year"],
    right_on=["county_name", "year"],
    how='left'
)


# Reordering columns for clarity
merged_df_final = merged_df_final[["county_name", "year",'GDP_PI',
                     'rent_50_0','rent_50_1','rent_50_2','rent_50_3','rent_50_4',
                     'housing_units','personal_income']]

merged_df_final

,county_name,year,GDP_PI,rent_50_0,rent_50_1,rent_50_2,rent_50_3,rent_50_4,housing_units,personal_income
0,ALBANY,2001,13068721.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ALBANY,2002,13424897.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ALBANY,2003,14257327.0,444.0,547.0,672.0,844.0,943.0,NaN,NaN
3,ALBANY,2004,14897956.0,444.0,548.0,673.0,844.0,943.0,NaN,NaN
4,ALBANY,2005,15541573.0,569.0,600.0,719.0,862.0,927.0,NaN,11476555.0
...,...,...,...,...,...,...,...,...,...,...
1686,YATES,2022,1170228.0,NaN,NaN,NaN,NaN,NaN,13113.0,1240781.0
1687,YATES,2023,1212637.0,709.0,806.0,1061.0,1419.0,1425.0,13143.0,NaN
1688,YATES,2024,1224869.0,767.0,862.0,1132.0,1440.0,1622.0,NaN,NaN
1689,YATES,2025,NaN,811.0,901.0,1182.0,1455.0,1879.0,NaN,NaN
1690,YATES,2026,NaN,790.0,873.0,1146.0,1388.0,1922.0,NaN,NaN

In [18]:
cols = ["GDP_PI", "housing_units", "personal_income"]

merged_df_final = merged_df_final.sort_values(["county_name", "year"])

merged_df_final[cols] = (
    merged_df_final
    .groupby("county_name")[cols]
    .transform(lambda x: x.bfill())
)

In [19]:
# Rechecking missing entries
merged_df_final.isna().sum()

county_name         0
year                0
GDP_PI             76
rent_50_0           0
rent_50_1           0
rent_50_2           0
rent_50_3           0
rent_50_4           0
housing_units      76
personal_income    76
dtype: int64

In [20]:
merged_df_final[merged_df_final.isnull().any(axis=1)]["year"].unique()

array([2001, 2002])

In [21]:
#Imputing for the two years
cols = ["GDP_PI", "housing_units", "personal_income"]

merged_df_final = merged_df_final.sort_values(
    ["county_name", "year"]
).copy()

# county-wise backward fill
for col in cols:
    merged_df_final[col] = (
        merged_df_final
        .groupby("county_name")[col]
        .transform(lambda x: x.bfill())
    )

# fallback global median
merged_df_final[cols] = (
    merged_df_final[cols]
    .fillna(merged_df_final[cols].median())
)

In [22]:
# Rechecking missing entries
merged_df_final.isnull().sum()

county_name        0
year               0
GDP_PI             0
rent_50_0          0
rent_50_1          0
rent_50_2          0
rent_50_3          0
rent_50_4          0
housing_units      0
personal_income    0
dtype: int64

In [23]:
# Converting data to long
rent_cols = [
    "rent_50_0",
    "rent_50_1",
    "rent_50_2",
    "rent_50_3",
    "rent_50_4"
]

merged_df_final_long = merged_df_final.melt(
    id_vars=[
        "county_name",
        "year",
        "GDP_PI",
        "housing_units",
        "personal_income"
    ],
    value_vars=rent_cols,
    var_name="house_size",
    value_name="rent"
)

# Extracting house size
merged_df_final_long["house_size"] = (
    merged_df_final_long["house_size"]
    .str.rsplit("_", n=1)
    .str[-1]
    .astype(int)
)

# Getting Rent Growth
merged_df_final_long = merged_df_final_long.sort_values(["county_name", "house_size", "year"])

merged_df_final_long["rent_growth"] = (
    merged_df_final_long.groupby(["county_name", "house_size"])["rent"]
    .pct_change()
)
merged_df_final_long

,county_name,year,GDP_PI,housing_units,personal_income,house_size,rent,rent_growth
0,ALBANY,2001,13068721.0,133501.0,11476555.0,0,444.0,NaN
1,ALBANY,2002,13424897.0,133501.0,11476555.0,0,444.0,0.000000
2,ALBANY,2003,14257327.0,133501.0,11476555.0,0,444.0,0.000000
3,ALBANY,2004,14897956.0,133501.0,11476555.0,0,444.0,0.000000
4,ALBANY,2005,15541573.0,133501.0,11476555.0,0,569.0,0.281532
...,...,...,...,...,...,...,...,...
8450,YATES,2022,1170228.0,13113.0,1240781.0,4,1176.0,0.000000
8451,YATES,2023,1212637.0,13143.0,1240781.0,4,1425.0,0.211735
8452,YATES,2024,1224869.0,13143.0,1240781.0,4,1622.0,0.138246
8453,YATES,2025,1224869.0,13143.0,1240781.0,4,1879.0,0.158446
8454,YATES,2026,1224869.0,13143.0,1240781.0,4,1922.0,0.022885

In [24]:
# Saving Data
merged_df_final.to_csv("merged_df_final.csv")
merged_df_final_long.to_csv("merged_df_final_long.csv")